// Auto-generated by @openelement/i18n — do not edit
export const locales = ["en","zh"];
export const defaultLocale = "en";

export function getDefaultLocale(): string { return defaultLocale; }
export function getI18nOptions() { return { locales, defaultLocale }; }
