// Auto-generated by @lessjs/content — do not edit
export const headerNav = [
  {
    "href": "/",
    "label": "Home"
  },
  {
    "href": "/docs",
    "label": "Docs"
  },
  {
    "href": "/examples",
    "label": "Examples"
  },
  {
    "href": "/components",
    "label": "Components"
  },
  {
    "href": "/architecture",
    "label": "Architecture"
  },
  {
    "href": "/hub",
    "label": "Hub"
  },
  {
    "href": "/roadmap",
    "label": "Roadmap"
  }
];
export const navSections = [
  {
    "section": "Principles",
    "items": [
      {
        "path": "/architecture",
        "label": "Architecture",
        "order": 0
      },
      {
        "path": "/architecture/protocols",
        "label": "Protocols",
        "order": 1
      },
      {
        "path": "/architecture/runtime-kernel",
        "label": "Runtime Kernel",
        "order": 2
      },
      {
        "path": "/architecture/adapter-vite",
        "label": "Adapter-Vite",
        "order": 3
      },
      {
        "path": "/architecture/package-graph",
        "label": "Package Graph",
        "order": 4
      },
      {
        "path": "/architecture/release-gates",
        "label": "Release Gates",
        "order": 5
      },
      {
        "path": "/engine/architecture",
        "label": "Architecture",
        "order": 10
      },
      {
        "path": "/engine/comparison",
        "label": "Comparison",
        "order": 20
      },
      {
        "path": "/engine/dsd",
        "label": "DSD Rendering",
        "order": 30
      },
      {
        "path": "/engine/islands",
        "label": "Island Upgrade",
        "order": 40
      },
      {
        "path": "/engine/islands-deep",
        "label": "Island Deep Dive",
        "order": 50
      }
    ]
  },
  {
    "section": "History",
    "items": [
      {
        "path": "/blog",
        "label": "Blog",
        "order": 10
      }
    ]
  },
  {
    "section": "Quick Start",
    "items": [
      {
        "path": "/docs",
        "label": "Docs",
        "order": 0
      },
      {
        "path": "/examples",
        "label": "Examples",
        "order": 1
      },
      {
        "path": "/components",
        "label": "Components",
        "order": 2
      },
      {
        "path": "/guide/architecture",
        "label": "Architecture",
        "order": 10
      },
      {
        "path": "/guide/positioning",
        "label": "Framework Positioning",
        "order": 10
      },
      {
        "path": "/guide/getting-started",
        "label": "Getting Started",
        "order": 20
      }
    ]
  },
  {
    "section": "Reference",
    "items": [
      {
        "path": "/engine/reference/core",
        "label": "API Reference",
        "order": 5
      },
      {
        "path": "/engine/design-system",
        "label": "Design System",
        "order": 10
      }
    ]
  },
  {
    "section": "Compatibility",
    "items": [
      {
        "path": "/engine/package-compatibility",
        "label": "Package Compatibility",
        "order": 10
      },
      {
        "path": "/engine/standards-registry",
        "label": "Standards & Registry",
        "order": 20
      }
    ]
  },
  {
    "section": "Core",
    "items": [
      {
        "path": "/guide/routing",
        "label": "Routing",
        "order": 10
      },
      {
        "path": "/guide/ssg",
        "label": "SSG/ISR/SSR Rendering",
        "order": 20
      },
      {
        "path": "/guide/islands",
        "label": "Islands & Hydration",
        "order": 25
      },
      {
        "path": "/guide/content-system",
        "label": "Content System",
        "order": 40
      },
      {
        "path": "/guide/api",
        "label": "API Routes",
        "order": 60
      },
      {
        "path": "/guide/rpc",
        "label": "RPC",
        "order": 70
      }
    ]
  },
  {
    "section": "Production",
    "items": [
      {
        "path": "/guide/configuration",
        "label": "Configuration",
        "order": 10
      },
      {
        "path": "/guide/security-middleware",
        "label": "Security & Middleware",
        "order": 20
      },
      {
        "path": "/guide/error-handling",
        "label": "Error Handling",
        "order": 30
      },
      {
        "path": "/guide/testing",
        "label": "Testing",
        "order": 40
      },
      {
        "path": "/guide/deployment",
        "label": "Deployment",
        "order": 50
      },
      {
        "path": "/guide/pwa",
        "label": "PWA Support",
        "order": 60
      }
    ]
  },
  {
    "section": "Guide",
    "items": [
      {
        "path": "/guide/jsx-components",
        "label": "JSX Components",
        "order": 7
      },
      {
        "path": "/zh/guide/jsx-components",
        "label": "JSX 组件",
        "order": 7
      },
      {
        "path": "/guide/static-props",
        "label": "Static Props",
        "order": 8
      },
      {
        "path": "/zh/guide/static-props",
        "label": "Static Props",
        "order": 8
      },
      {
        "path": "/guide/signal-reactivity",
        "label": "Signal Reactivity",
        "order": 9
      },
      {
        "path": "/zh/guide/signal-reactivity",
        "label": "Signal 响应式",
        "order": 9
      },
      {
        "path": "/guide/migration-v0.24",
        "label": "Migration (v0.24)",
        "order": 10
      },
      {
        "path": "/zh/guide/migration-v0.24",
        "label": "v0.24 迁移指南",
        "order": 10
      }
    ]
  },
  {
    "section": "Registry",
    "items": [
      {
        "path": "/hub",
        "label": "Hub",
        "order": 0
      },
      {
        "path": "/registry",
        "label": "Package Registry",
        "order": 5
      },
      {
        "path": "/registry/:package/:component",
        "label": "Component Detail",
        "order": 6
      }
    ]
  },
  {
    "section": "Roadmap & Decisions",
    "items": [
      {
        "path": "/zh/decisions/20260515-1-renderer-kernel-registry-sop",
        "label": "20260515 Renderer SOP",
        "order": 30
      }
    ]
  }
];
