// Auto-generated by @lessjs/content — do not edit
export const headerNav = [
  {
    "href": "/guide/getting-started",
    "label": "Guide"
  },
  {
    "href": "/apilist",
    "label": "API"
  },
  {
    "href": "/architecture/architecture",
    "label": "Architecture"
  },
  {
    "href": "/registry",
    "label": "Hub"
  },
  {
    "href": "/blog",
    "label": "Blog"
  }
];
export const navSections = [
  {
    "section": "Reference",
    "items": [
      {
        "path": "/apilist",
        "label": "API Reference",
        "order": 5
      }
    ]
  },
  {
    "section": "History",
    "items": [
      {
        "path": "/blog",
        "label": "Blog",
        "order": 10
      }
    ]
  },
  {
    "section": "Quick Start",
    "items": [
      {
        "path": "/docs",
        "label": "Docs",
        "order": 0
      },
      {
        "path": "/guide/architecture",
        "label": "Architecture",
        "order": 10
      }
    ]
  },
  {
    "section": "Registry",
    "items": [
      {
        "path": "/hub",
        "label": "Hub",
        "order": 0
      },
      {
        "path": "/registry",
        "label": "Package Registry",
        "order": 5
      },
      {
        "path": "/registry/:package/:component",
        "label": "Component Detail",
        "order": 6
      }
    ]
  }
];
