/**
 * Runtime Shim Generator
 *
 * Generates `packages/core/src/runtime-shim.ts` from the canonical source files:
 *   - packages/core/src/html-escape.ts
 *   - packages/core/src/render-dsd.ts
 *   - packages/core/src/render-nested.ts (parse5-based, build-time only)
 *
 * Strategy: Use TypeScript's own transpiler (ts.transpileModule) to reliably
 * convert TypeScript → JavaScript, then extract individual functions using
 * TypeScript's AST parser (robust against regex literals, template literals, etc.)
 *
 * Usage: deno task generate:runtime-shim
 * Verify: deno task generate:runtime-shim && git diff --exit-code packages/core/src/runtime-shim.ts
 */

import * as ts from 'typescript';
import { relative, resolve } from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';

const REPO_ROOT = resolve(import.meta.dirname ?? '.', '../../..');
const PKG_SRC = resolve(REPO_ROOT, 'packages/core/src');
const OUT_PATH = resolve(PKG_SRC, 'runtime-shim.ts');

// ─── Function Map ───────────────────────────────────────────────

const FUNCTION_MAP = [
  {
    source: resolve(PKG_SRC, 'html-escape.ts'),
    functions: ['escapeHtml', 'escapeAttr', 'escapeAttrValue', 'wrapInDocument'],
  },
  {
    source: resolve(PKG_SRC, 'render-dsd.ts'),
    functions: ['serializeAttributes', 'buildDsdTemplateAttrs', 'renderDSD', 'renderDSDByName'],
  },
  {
    source: resolve(PKG_SRC, 'render-nested.ts'),
    functions: [
      'kebabToCamel',
      'parseAttrsToProps',
      'elementAlreadyHasDSD',
      'isCustomElementName',
      'inferDsdOptions',
      'isInsideDsdTemplate',
      'renderNestedCustomElements',
    ],
  },
];

// ─── Shim Boilerplate ──────────────────────────────────────────

const SHIM_BOILERPLATE = `export { Hono } from 'hono';
import * as parse5 from 'parse5';

// ─── Adapter Protocol ──────────────────────────────────────────
var _adapter = undefined;

export function registerAdapter(adapter) {
  _adapter = adapter;
}

function getAdapter() {
  return _adapter;
}

function isLitTemplateResultHeuristic(value) {
  return typeof value === 'object' && value !== null && '_$litType$' in value;
}

// ─── Shim Logger ───────────────────────────────────────────────
// Minimal logger stub — maps structured log calls to console with [LessJS] prefix.
// Source files use createLogger('core') which adds the prefix at runtime;
// the shim reproduces this with a static stub.
var log = {
  error: function() { var a = ['[LessJS]']; a.push.apply(a, arguments); console.error.apply(console, a); },
  warn: function() { var a = ['[LessJS]']; a.push.apply(a, arguments); console.warn.apply(console, a); },
  debug: function() { var a = ['[LessJS]']; a.push.apply(a, arguments); console.debug.apply(console, a); },
  info: function() { var a = ['[LessJS]']; a.push.apply(a, arguments); console.log.apply(console, a); },
};
`;

// ─── File Header ────────────────────────────────────────────────

function fileHeader(): string {
  const sources = FUNCTION_MAP.map((e) =>
    ` *   - ${relative(REPO_ROOT, e.source).replace(/\\/g, '/')}`
  ).join('\n');
  return `/**
 * ⚠️ AUTO-GENERATED by \`deno task generate:runtime-shim\` — do not edit.
 *
 * Source files:
${sources}
 *
 * To regenerate: deno task generate:runtime-shim
 * To verify: deno task generate:runtime-shim && git diff --exit-code packages/core/src/runtime-shim.ts
 */`;
}

// ─── Transpile source file ──────────────────────────────────────

function transpileSource(filePath: string): string {
  const sourceText = readFileSync(filePath, 'utf-8');
  const result = ts.transpileModule(sourceText, {
    compilerOptions: {
      target: ts.ScriptTarget.ESNext,
      module: ts.ModuleKind.ESNext,
      strict: false,
      esModuleInterop: true,
      skipLibCheck: true,
    },
  });
  return result.outputText;
}

// ─── Extract a named function from JS source ─────────────────────

/**
 * Extract a named function from transpiled JS source using TypeScript's
 * own AST parser. This correctly handles regex literals, template literals,
 * and all JS syntax — no manual brace matching needed.
 */
function extractFunctionFromJs(jsSource: string, functionName: string): string {
  const sourceFile = ts.createSourceFile(
    'temp.js',
    jsSource,
    ts.ScriptTarget.Latest,
    true, // setParentNodes
    ts.ScriptKind.JS,
  );

  let result: string | null = null;

  function visit(node: ts.Node): void {
    if (ts.isFunctionDeclaration(node) && node.name?.text === functionName) {
      // getStart() skips leading trivia (whitespace/comments)
      const start = node.getStart(sourceFile);
      const end = node.end;
      let text = jsSource.slice(start, end);
      // Strip 'export ' prefix — shim uses bare function declarations
      text = text.replace(/^export\s+/, '');
      result = text;
      return;
    }
    ts.forEachChild(node, visit);
  }

  ts.forEachChild(sourceFile, visit);

  if (result === null) {
    throw new Error(`Function "${functionName}" not found in transpiled output`);
  }

  return result;
}

// ─── Post-processing: clean up transpiled JS for the shim ────────

function cleanForShim(code: string): string {
  // Remove `export { ... }` re-export statements
  code = code.replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '');
  // Remove import statements
  code = code.replace(/^import\s+.*?;?\s*$/gm, '');
  // Replace dynamic import of render-dsd with local reference
  // (renderDSD is defined in the same shim file)
  code = code.replace(
    /const\s*\{\s*renderDSD\s*\}\s*=\s*await\s+import\s*\(\s*['"]\.\/render-dsd\.js['"]\s*\)\s*;/g,
    '// renderDSD is defined in this file',
  );
  return code.trim();
}

// ─── Main Generator ─────────────────────────────────────────────

function generate(): void {
  const sections: string[] = [];

  for (const entry of FUNCTION_MAP) {
    const jsSource = transpileSource(entry.source);
    const functions: string[] = [];

    for (const funcName of entry.functions) {
      const fnText = extractFunctionFromJs(jsSource, funcName);
      const cleaned = cleanForShim(fnText);
      functions.push(cleaned);
    }

    if (functions.length > 0) {
      sections.push(functions.join('\n\n'));
    }
  }

  // ─── Assemble the shim content ────────────────────────────────

  const shimParts: string[] = [];
  shimParts.push(fileHeader());
  shimParts.push(SHIM_BOILERPLATE.trim());
  for (const section of sections) {
    shimParts.push(section);
  }

  const shimContent = shimParts.join('\n\n');

  // ─── Wrap in createRuntimeShimCode() ──────────────────────────

  const output = `export function createRuntimeShimCode(): string {\n  return ${
    JSON.stringify(shimContent)
  };\n}\n`;

  writeFileSync(OUT_PATH, output, 'utf-8');
  console.log(`Generated: ${relative(REPO_ROOT, OUT_PATH).replace(/\\/g, '/')}`);
}

// ─── Run ────────────────────────────────────────────────────────

try {
  generate();
} catch (err) {
  console.error('Generation failed:', err);
  Deno.exit(1);
}
