/**
 * Build-time runtime shim generation.
 *
 * Vite/Rolldown does not resolve JSR bare specifiers inside generated virtual
 * modules. The LessJS plugin writes this small local file into `.less/` and
 * aliases `@lessjs/core/less-runtime` to it so generated SSR entries stay
 * package-manager agnostic.
 *
 * ⚠️  MAINTENANCE WARNING ⚠️
 * This file is a HAND-MAINTAINED code generator that mirrors the logic in
 * `render-dsd.ts`. When you modify render-dsd.ts, you MUST also update this
 * file to keep them in sync. Key areas to watch:
 *   - escapeHtml / escapeAttr
 *   - serializeAttributes
 *   - findTemplateShadowRanges regex
 *   - alreadyHasDSD regex
 *   - renderNestedCustomElements algorithm
 *   - renderDSD main function
 *   - buildDsdTemplateAttrs / inferDsdOptions
 *   - DsdOptions / ComponentLayer (v0.6.2: pure-island skips DSD)
 *
 * Long-term direction: replace with AST-based code generation from render-dsd.ts.
 *
 * v0.6.2: Mirrors render-dsd.ts with three-layer model (pure-island skips DSD),
 * error visibility, data-ssr-props, nested DSD, slot/projection support,
 * and WHATWG DSD options.
 */

export function createRuntimeShimCode(): string {
  return `/**
 * Auto-generated by @lessjs/core.
 * Do not edit directly.
 */

export { Hono } from 'hono';

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function escapeAttrValue(value) {
  if (value == null) return '';
  return escapeAttr(String(value));
}

function serializeAttributes(props = {}) {
  const parts = [];
  for (const [key, val] of Object.entries(props)) {
    if (val === false || val === null || val === undefined) continue;
    if (val === true) parts.push(key);
    else if (typeof val === 'object') parts.push(\`\${key}="\${escapeAttrValue(JSON.stringify(val))}"\`);
    else parts.push(\`\${key}="\${escapeAttrValue(val)}"\`);
  }
  return parts.length > 0 ? ' ' + parts.join(' ') : '';
}

// ─── Adapter Protocol ──────────────────────────────────────────
var _adapter = undefined;

export function registerAdapter(adapter) {
  _adapter = adapter;
}

function getAdapter() {
  return _adapter;
}

function isLitTemplateResultHeuristic(value) {
  return typeof value === 'object' && value !== null && '_$litType$' in value;
}

// ─── Nested DSD helpers ──────────────────────────────────────

function kebabToCamel(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function parseElementAttrs(attrsStr) {
  const props = {};
  const attrRegex = /(\\w[\\w-]*)(?:="((?:[^"\\\\]|\\\\.)*)"|='((?:[^'\\\\]|\\\\.)*)')?/g;
  let match;
  while ((match = attrRegex.exec(attrsStr)) !== null) {
    const key = match[1];
    const value = match[2] ?? match[3];
    if (value === undefined) {
      props[key] = true;
    } else if (key.startsWith('data-')) {
      props[key] = value;
    } else {
      props[kebabToCamel(key)] = value;
    }
  }
  return props;
}

function findMatchingCloseTag(html, tagName, searchFrom) {
  let depth = 1;
  const openRegex = new RegExp(\`<\${tagName}[\\\\s/>]\`, 'g');
  const closeRegex = new RegExp(\`</\${tagName}>\`, 'g');
  openRegex.lastIndex = searchFrom;
  closeRegex.lastIndex = searchFrom;
  let nextOpen = openRegex.exec(html);
  let nextClose = closeRegex.exec(html);
  while (depth > 0) {
    if (nextClose === null) return -1;
    if (nextOpen === null || nextOpen.index >= nextClose.index) {
      depth--;
      if (depth === 0) return nextClose.index;
      nextClose = closeRegex.exec(html);
    } else {
      depth++;
      nextOpen = openRegex.exec(html);
    }
  }
  return -1;
}

function findTemplateShadowRanges(html) {
  const ranges = [];
  // v0.6.2 fix: must match additional DSD attributes (shadowrootdelegatesfocus, etc.)
  // not just <template shadowrootmode="open"> but also
  // <template shadowrootmode="open" shadowrootdelegatesfocus>
  const templateOpenRegex = /<template\\s+shadowrootmode\\s*=\\s*"open"[^>]*>/g;
  let match;
  while ((match = templateOpenRegex.exec(html)) !== null) {
    const contentStart = match.index + match[0].length;
    let depth = 1;
    let searchPos = contentStart;
    while (depth > 0 && searchPos < html.length) {
      const nextClose = html.indexOf('</template>', searchPos);
      const nextOpen = html.indexOf('<template', searchPos);
      if (nextClose === -1) break;
      if (nextOpen !== -1 && nextOpen < nextClose) {
        depth++;
        searchPos = nextOpen + 9;
      } else {
        depth--;
        if (depth === 0) {
          ranges.push([match.index, nextClose + '</template>'.length]);
        }
        searchPos = nextClose + '</template>'.length;
      }
    }
  }
  return ranges;
}

function isInRange(pos, ranges) {
  for (const [start, end] of ranges) {
    if (pos >= start && pos < end) return true;
  }
  return false;
}

function alreadyHasDSD(html, openEnd, _closeIdx) {
  const content = html.slice(openEnd);
  // v0.6.2 fix: must accept additional DSD attributes after shadowrootmode="open"
  // otherwise components with delegatesFocus=true cause an infinite loop
  const match = content.match(/^\\s*<template\\s+shadowrootmode\\s*=\\s*"open"[^>]*>/);
  return match !== null;
}

// ─── DSD Options (WHATWG) ─────────────────────────────────────

function buildDsdTemplateAttrs(options) {
  if (!options) return '';
  var parts = [];
  if (options.delegatesFocus) parts.push(' shadowrootdelegatesfocus');
  if (options.serializable) parts.push(' shadowrootserializable');
  if (options.slotAssignment === 'manual') parts.push(' shadowrootslotassignment="manual"');
  if (options.customElementRegistry) {
    parts.push(' shadowrootcustomelementregistry="' + escapeAttr(options.customElementRegistry) + '"');
  }
  return parts.join('');
}

function inferDsdOptions(tagName, cls) {
  var opts = {};
  if (cls.delegatesFocus === true) opts.delegatesFocus = true;
  if (cls.serializable === true) opts.serializable = true;
  if (cls.slotAssignment === 'manual') opts.slotAssignment = 'manual';
  if (typeof cls.customElementRegistry === 'string') opts.customElementRegistry = cls.customElementRegistry;
  return opts;
}

async function renderNestedCustomElements(html) {
  if (!globalThis.customElements?.get) return html;

  let result = html;
  let maxIterations = 50;

  while (maxIterations-- > 0) {
    const shadowRanges = findTemplateShadowRanges(result);
    const ceOpenRegex = /<([a-z][a-z0-9]*-[a-z0-9-]+)([\\s\\S]*?)>/g;
    let deepestPos = null;

    let match;
    while ((match = ceOpenRegex.exec(result)) !== null) {
      const tagName = match[1];
      const attrsStr = match[2];
      const openStart = match.index;
      const openEnd = openStart + match[0].length;

      if (!globalThis.customElements.get(tagName)) continue;
      if (isInRange(openStart, shadowRanges)) continue;

      const selfClosing = attrsStr.trimEnd().endsWith('/');
      if (selfClosing) {
        if (!deepestPos || openStart > deepestPos.start) {
          deepestPos = { tagName, attrsStr: attrsStr.replace(/\\/\\s*\$/, ''), start: openStart, openEnd, selfClosing: true };
        }
        continue;
      }

      const closeIdx = findMatchingCloseTag(result, tagName, openEnd);
      if (closeIdx === -1) continue;
      if (alreadyHasDSD(result, openEnd, closeIdx)) continue;
      if (isInRange(closeIdx, shadowRanges)) continue;

      if (!deepestPos || openStart > deepestPos.start) {
        deepestPos = { tagName, attrsStr, start: openStart, openEnd, selfClosing: false };
      }
    }

    if (!deepestPos) break;

    const pos = deepestPos;
    const Cls = globalThis.customElements.get(pos.tagName);
    const props = parseElementAttrs(pos.attrsStr);
    const dsdOpts = inferDsdOptions(pos.tagName, Cls);

    if (pos.selfClosing) {
      const dsdHtml = await renderDSD(pos.tagName, Cls, props, undefined, dsdOpts);
      result = result.slice(0, pos.start) + dsdHtml + result.slice(pos.openEnd);
    } else {
      const closeIdx = findMatchingCloseTag(result, pos.tagName, pos.openEnd);
      if (closeIdx === -1) break;
      const closeEnd = closeIdx + \`</\${pos.tagName}>\`.length;
      const lightDom = result.slice(pos.openEnd, closeIdx);
      const dsdHtml = await renderDSD(pos.tagName, Cls, props, undefined, dsdOpts);

      const templateClose = '</template>';
      const templateIdx = dsdHtml.lastIndexOf(templateClose);
      if (templateIdx === -1) break;

      const lightDomTrimmed = lightDom.trim();
      let finalHtml;
      if (!lightDomTrimmed) {
        finalHtml = dsdHtml;
      } else {
        const before = dsdHtml.slice(0, templateIdx + templateClose.length);
        const after = dsdHtml.slice(templateIdx + templateClose.length);
        finalHtml = before + '\\n  ' + lightDom + after;
      }

      result = result.slice(0, pos.start) + finalHtml + result.slice(closeEnd);
    }
  }

  return result;
}

// ─── Main renderDSD ────────────────────────────────────────────

export async function renderDSD(tagName, componentClass, props = {}, sourceInfo, dsdOptions) {
  const sourceStr = sourceInfo
    ? (sourceInfo.route ? \` route="\${sourceInfo.route}"\` : '') + (sourceInfo.source ? \` source="\${sourceInfo.source}"\` : '')
    : '';

  // 1. Instantiate
  let instance;
  try {
    instance = new componentClass();
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    console.error(\`[LessJS] Failed to instantiate <\${tagName}>:\`, errMsg);
    return \`<\${tagName}\${sourceStr}><!-- LessJS ERROR: Failed to instantiate <\${tagName}>: \${escapeHtml(errMsg)} -->\`
      + (sourceInfo?.route ? \`\\n<!-- Route: \${escapeHtml(sourceInfo.route)} -->\` : '')
      + (sourceInfo?.source ? \`\\n<!-- Source: \${escapeHtml(sourceInfo.source)} -->\` : '')
      + \`</\${tagName}>\`;
  }

  // 2. Set props
  for (const [key, value] of Object.entries(props)) {
    try { instance[key] = value; } catch (e) { /* read-only property — safe to skip */ console.debug(\`[LessJS] Cannot set read-only property "\${key}" on <\${tagName}>\`); }
  }

  // 3. Render
  let content;
  try {
    const result = instance.render();
    if (result == null) {
      content = '';
    } else if (typeof result === 'string') {
      content = result;
    } else {
      const adapter = getAdapter();
      if (adapter?.isTemplate && adapter?.render && adapter.isTemplate(result)) {
        content = await adapter.render(result, tagName);
      } else {
        const errDetail = isLitTemplateResultHeuristic(result)
          ? 'This looks like a Lit TemplateResult; install @lessjs/adapter-lit to handle it.'
          : \`Components must return a string from render(), got \${typeof result}.\`;
        console.error(\`[LessJS] <\${tagName}> render() returned \${typeof result} instead of string. \${errDetail}\`);
        content = \`<!-- LessJS ERROR: <\${tagName}> render() returned \${typeof result}, expected string. \${errDetail} -->\`;
      }
    }
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    const errStack = err instanceof Error ? err.stack : '';
    console.error(\`[LessJS] <\${tagName}> render() failed:\`, errMsg, errStack ? \`\\n\${errStack}\` : '');
    content = \`<!-- LessJS ERROR: <\${tagName}> render() threw: \${escapeHtml(errMsg)} -->\\n\`
      + (errStack ? \`<!-- Stack: \${escapeHtml(errStack.split('\\\\n').slice(0, 3).join(' | '))} -->\\n\` : '')
      + '<!-- Check console for full error details -->';
  }

  // Nested DSD
  content = await renderNestedCustomElements(content);

  // Styles extraction
  let styleCss = '';
  const adapter = getAdapter();
  if (adapter?.extractStyles) {
    try { styleCss = adapter.extractStyles(componentClass) || ''; } catch (e) { console.debug(\`[LessJS] extractStyles failed for <\${tagName}>: \${e instanceof Error ? e.message : String(e)}\`); }
  }

  // data-ssr-props
  const resolvedLayer = dsdOptions?.layer || instance.layer || 'dsd-static';
  const attrs = serializeAttributes(props);
  const ssrPropsAttr = Object.keys(props).length > 0
    ? \` data-ssr-props="\${escapeAttrValue(JSON.stringify(props))}"\`
    : '';

  // v0.6.2: Layer 3 (pure-island) — no DSD template, framework owns shadow root
  if (resolvedLayer === 'pure-island') {
    return \`<\${tagName}\${attrs}\${ssrPropsAttr}\${sourceStr}></\${tagName}>\`;
  }

  // Layer 1/2: emit DSD template
  const styleTag = styleCss ? \`\\\\n    <style>\${styleCss}</style>\` : '';
  const dsdAttrs = buildDsdTemplateAttrs(dsdOptions);
  return \`<\${tagName}\${attrs}\${ssrPropsAttr}\${sourceStr}>
  <template shadowrootmode="open"\${dsdAttrs}>\${styleTag}
    \${content}
  </template>
</\${tagName}>\`;
}

export async function renderDSDByName(tagName, props = {}, sourceInfo, dsdOptions) {
  const cls = globalThis.customElements?.get(tagName);
  if (!cls) {
    console.warn(\`[LessJS] <\${tagName}> is not registered; rendering as void element\`);
    const attrs = serializeAttributes(props);
    return \`<\${tagName}\${attrs}></\${tagName}>\`;
  }
  return await renderDSD(tagName, cls, props, sourceInfo, dsdOptions);
}

export function wrapInDocument(html, options = {}) {
  const {
    title = 'LessJS',
    lang = 'en',
    clientScript = '',
    meta,
    devMode = false,
    routeModulePath,
    headExtras = '',
    cspNonce,
  } = options;
  const nonceAttr = cspNonce ? \` nonce="\${cspNonce}"\` : '';
  // Security: warn if headExtras contains <script> tags
  if (headExtras && /<script[\\s>]/i.test(headExtras)) {
    console.warn('[LessJS] headExtras contains <script> tags. Ensure this is developer-controlled content to prevent XSS. Use inject.scripts for safe URL injection.');
  }
  const metaTags = [];
  if (meta?.description) {
    metaTags.push(\`  <meta name="description" content="\${escapeAttr(meta.description)}">\`);
  }
  const metaBlock = metaTags.length > 0 ? '\\\\n' + metaTags.join('\\\\n') + '\\\\n' : '';
  const devScripts = devMode
    ? \`
  <script type="module" src="/@vite/client"\${nonceAttr}></script>
  \${routeModulePath ? \`<script type="module"\${nonceAttr}>
  import '\${routeModulePath}';
</script>\` : ''}\`
    : '';

  return \`<!DOCTYPE html>
<html lang="\${escapeAttr(lang)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>\${escapeHtml(title)}</title>\${metaBlock}
  \${headExtras}
</head>
<body>
  \${html}
  \${clientScript}\${devScripts}
</body>
</html>\`;
}
`;
}
