/**
 * Build-time runtime shim generation.
 *
 * Vite/Rolldown does not resolve JSR bare specifiers inside generated virtual
 * modules. The KISS plugin writes this small local file into `.kiss/` and
 * aliases `@lessjs/core/less-runtime` to it so generated SSR entries stay
 * package-manager agnostic.
 */

export function createRuntimeShimCode(): string {
  return `/**
 * Auto-generated by @lessjs/core.
 * Do not edit directly.
 */

export { Hono } from 'hono';

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function serializeAttributes(props = {}) {
  const parts = [];
  for (const [key, val] of Object.entries(props)) {
    if (val === false || val === null || val === undefined) continue;
    if (val === true) parts.push(key);
    else parts.push(\`\${key}="\${escapeAttr(val)}"\`);
  }
  return parts.length > 0 ? ' ' + parts.join(' ') : '';
}

function getAdapterTemplateCheck() {
  return globalThis.__kissLitTemplateCheck;
}

function getAdapterSsrRenderer() {
  return globalThis.__kissLitSsrRenderer;
}

function getAdapterStylesExtractor() {
  return globalThis.__kissLitStylesExtractor;
}

function isLitTemplateResultHeuristic(value) {
  return typeof value === 'object' && value !== null && '_$litType$' in value;
}

export async function renderDSD(tagName, componentClass, props = {}) {
  let instance;
  try {
    instance = new componentClass();
  } catch (err) {
    console.error(\`[LessJS] Failed to instantiate <\${tagName}>:\`, err);
    return \`<\${tagName}><!-- render error --></\${tagName}>\`;
  }

  for (const [key, value] of Object.entries(props)) {
    try {
      instance[key] = value;
    } catch {
      // Ignore read-only properties during SSR.
    }
  }

  let content;
  try {
    const result = instance.render();
    if (result == null) {
      content = '';
    } else if (typeof result === 'string') {
      content = result;
    } else {
      const templateCheck = getAdapterTemplateCheck();
      const ssrRenderer = getAdapterSsrRenderer();
      if (templateCheck && ssrRenderer && templateCheck(result)) {
        content = await ssrRenderer(result, tagName);
      } else {
        console.error(
          \`[LessJS] <\${tagName}> render() returned \${typeof result} instead of string. \` +
            (isLitTemplateResultHeuristic(result)
              ? 'This looks like a Lit TemplateResult; install @lessjs/adapter-lit to handle it.'
              : 'Components must return a string from render().'),
        );
        content = \`<!-- render error: \${typeof result} returned, expected string -->\`;
      }
    }
  } catch (err) {
    console.error(\`[LessJS] <\${tagName}> render() failed:\`, err);
    content = '<!-- render error -->';
  }

  let styleCss = '';
  const stylesExtractor = getAdapterStylesExtractor();
  if (stylesExtractor) {
    try {
      styleCss = stylesExtractor(componentClass) || '';
    } catch {
      // Continue without extracted styles.
    }
  }

  const attrs = serializeAttributes(props);
  const styleTag = styleCss ? \`\\n    <style>\${styleCss}</style>\` : '';
  return \`<\${tagName}\${attrs}>
  <template shadowrootmode="open">\${styleTag}
    \${content}
  </template>
</\${tagName}>\`;
}

export async function renderDSDByName(tagName, props = {}) {
  const cls = globalThis.customElements?.get(tagName);
  if (!cls) {
    console.warn(\`[LessJS] <\${tagName}> is not registered; rendering as void element\`);
    const attrs = serializeAttributes(props);
    return \`<\${tagName}\${attrs}></\${tagName}>\`;
  }
  return await renderDSD(tagName, cls, props);
}

export function wrapInDocument(html, options = {}) {
  const {
    title = 'LessJS',
    lang = 'en',
    clientScript = '',
    meta,
    devMode = false,
    routeModulePath,
    headExtras = '',
    cspNonce,
  } = options;
  const nonceAttr = cspNonce ? \` nonce="\${cspNonce}"\` : '';
  const metaTags = [];
  if (meta?.description) {
    metaTags.push(\`  <meta name="description" content="\${escapeAttr(meta.description)}">\`);
  }
  const metaBlock = metaTags.length > 0 ? '\\n' + metaTags.join('\\n') + '\\n' : '';
  const devScripts = devMode
    ? \`
  <script type="module" src="/@vite/client"\${nonceAttr}></script>
  \${routeModulePath ? \`<script type="module"\${nonceAttr}>
  import '\${routeModulePath}';
</script>\` : ''}\`
    : '';

  return \`<!DOCTYPE html>
<html lang="\${escapeAttr(lang)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>\${escapeHtml(title)}</title>\${metaBlock}
  \${headExtras}
</head>
<body>
  \${html}
  \${clientScript}\${devScripts}
</body>
</html>\`;
}
`;
}
