/**
 * @lessjs/core - SSG Post-Processing
 *
 * Pure Node.js fs operations for SSG output post-processing.
 * No Vite dependency — these functions only read/write files.
 *
 * v0.3.0: buildIslandChunkMap reads Rollup manifest (generated by
 * build.ts with manifest:true) instead of grep-ing JS file contents.
 * This is deterministic and immune to false positives from comments
 * or third-party code containing tagName strings.
 *
 * v0.3.1: HTML insertion uses robust regex-based helpers instead of
 * naive string replace(). Handles edge cases like whitespace around
 * tags, attributes on target tags, and varying case — without requiring
 * a heavy HTML parser dependency (parse5 ~200KB). The tradeoff:
 *   - ✅ Zero dependencies beyond Node.js builtins
 *   - ✅ Handles all well-formed HTML5 output from Hono toSSG()
 *   - ⚠️  Not a general-purpose parser — only handles our specific
 *     insertion patterns (after <head>, before </body>, path rewrites)
 */

import { join, resolve } from 'node:path';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';

// ─── Lightweight HTML Insertion Helpers ───────────────────────────────
// These handle the edge cases that naive .replace() misses:
//   - <head lang="en">  (attributes on target tag)
//   - </body>  (whitespace before/inside close tag)
//   - <HEAD>, </BODY>  (case variance in legacy HTML)
//
// We DON'T use parse5 because:
//   1. SSG output from Hono/toSSG() is always well-formed HTML5
//   2. Our operations are 3 specific insertions, not arbitrary DOM manipulation
//   3. Adding 200KB+ dependency violates KISS philosophy

/** Insert content immediately after <head> opening tag (handles attributes) */
function insertAfterHead(html: string, content: string): string {
  // Match <head> with optional attributes, case-insensitive
  const headMatch = html.match(/<head(\s[^>]*)?>/i);
  if (!headMatch) {
    // Fallback: try inserting at start of document (before <html>)
    // This handles edge cases where <head> might be omitted
    return html.startsWith('<!') || html.startsWith('<html')
      ? html.replace(/(<(?:!DOCTYPE|html)[^>]*>)/i, `$1\n<head>\n  ${content}\n</head>`)
      : `<head>\n  ${content}\n</head>\n${html}`;
  }
  const headEnd = headMatch.index! + headMatch[0].length;
  return html.slice(0, headEnd) + `\n  ${content}` + html.slice(headEnd);
}

/** Insert content immediately before </body> closing tag */
function insertBeforeBodyClose(html: string, content: string): string {
  // Match </body> with optional whitespace inside/close
  const bodyCloseMatch = html.match(/<\/body\s*>/i);
  if (!bodyCloseMatch) {
    // No </body> found — append at end
    return html + `\n${content}\n`;
  }
  const idx = bodyCloseMatch.index!;
  return html.slice(0, idx) + `${content}\n` + html.slice(idx);
}

// ─── Public API ────────────────────────────────────────────────────────

/**
 * Scan client build output to build tagName → chunk path mapping.
 *
 * v0.3.0: Reads Rollup manifest JSON instead of grep-ing file contents.
 * The manifest is generated by build.ts with `manifest: true` in the
 * client build's Rollup output options.
 */
export function buildIslandChunkMap(
  root: string,
  outDir: string,
  islands: string[],
  basePath: string = '/',
): Record<string, string> {
  const distDir = resolve(root, outDir);
  const clientDir = resolve(distDir, 'client');
  const islandChunkMap: Record<string, string> = {};

  if (!existsSync(clientDir)) return islandChunkMap;

  // v0.3.0: Read Rollup manifest (deterministic, build-time metadata)
  const manifestPath = join(clientDir, '.vite', 'manifest.json');
  if (existsSync(manifestPath)) {
    try {
      const manifestRaw = readFileSync(manifestPath, 'utf-8');
      const manifest = JSON.parse(manifestRaw);

      // Manifest keys are source paths, values have file: output path
      // e.g. { "src/islands/code-block.ts": { "file": "islands/island-code-block-abc.js", ... } }
      // NOTE: entry.file already includes the "islands/" prefix, so we use client/${entry.file}
      //       (not client/islands/${entry.file} which would double the prefix)
      for (const [_srcPath, entry] of Object.entries(manifest) as [string, { file?: string }][]) {
        if (!entry.file) continue;
        // Match island tagName from chunk name: island-<tagName>-hash.js
        const chunkMatch = entry.file.match(/^islands\/island-(.+?)-[A-Za-z0-9]+\.js$/);
        if (chunkMatch && islands.includes(chunkMatch[1])) {
          islandChunkMap[chunkMatch[1]] = `${basePath}client/${entry.file}`;
        }
        // Also match client entry
        if (entry.file === 'islands/client.js') {
          for (const tagName of islands) {
            if (!islandChunkMap[tagName]) {
              islandChunkMap[tagName] = `${basePath}client/islands/client.js`;
            }
          }
        }
      }
    } catch {
      // Fall through to legacy approach if manifest is malformed
    }
  }

  // Fallback: if manifest not found or empty, scan island chunks directly
  if (Object.keys(islandChunkMap).length === 0) {
    const islandsBuildDir = join(clientDir, 'islands');
    if (existsSync(islandsBuildDir)) {
      const files = readdirSync(islandsBuildDir);
      for (const file of files) {
        if (!file.endsWith('.js')) continue;
        // Match island-<tagName>-<hash>.js pattern
        const match = file.match(/^island-(.+?)-[A-Za-z0-9]+\.js$/);
        if (match && islands.includes(match[1])) {
          islandChunkMap[match[1]] = `${basePath}client/islands/${file}`;
        }
      }
    }
  }

  // Last resort: point all islands to client.js
  if (Object.keys(islandChunkMap).length === 0) {
    const clientEntry = join(clientDir, 'islands', 'client.js');
    if (existsSync(clientEntry)) {
      for (const tagName of islands) {
        islandChunkMap[tagName] = `${basePath}client/islands/client.js`;
      }
    }
  }

  return islandChunkMap;
}

/**
 * Inject client script tag into all HTML files.
 *
 * After SSG rendering, each HTML file needs a <script> tag that loads
 * the Vite-built client entry. This entry imports island modules so
 * custom elements can self-register and upgrade existing DSD markup.
 *
 * Uses insertBeforeBodyClose() for robustness against whitespace/case issues.
 */
export function injectClientScript(dir: string, scriptSrc: string): void {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      injectClientScript(fullPath, scriptSrc);
    } else if (entry.name.endsWith('.html')) {
      let content = readFileSync(fullPath, 'utf-8');
      const scriptTag = `  <script type="module" src="${scriptSrc}"></script>`;
      // Only inject if not already present (check both quoted variants)
      if (!content.includes(scriptSrc)) {
        content = insertBeforeBodyClose(content, scriptTag);
        writeFileSync(fullPath, content, 'utf-8');
      }
    }
  }
}

/**
 * Inject CSP <meta> tag into all HTML files (SSG-only).
 *
 * For static sites, CSP is enforced via <meta http-equiv="Content-Security-Policy">
 * rather than HTTP headers. Note: nonce-based CSP is NOT supported for SSG
 * (nonces must be per-request and unpredictable — impossible in static files).
 *
 * If csp.nonce is true, this function logs a warning and falls back to
 * policy-only mode without nonce.
 *
 * Uses insertAfterHead() for robustness against <head> attributes.
 */
export function injectCspMeta(
  dir: string,
  cspPolicy: string,
  reportOnly = false,
  nonce = false,
): void {
  // SSG outputs static HTML files — CSP nonces must be per-request and
  // unpredictable, which is impossible in static files. If nonce mode is
  // requested, warn the user and fall back to policy-only mode.
  if (nonce) {
    console.warn(
      '[LessJS] CSP nonce is not supported for SSG static output. ' +
        'Falling back to policy-only Content-Security-Policy meta tag. ' +
        'For per-request nonces, use a server-side middleware instead.',
    );
  }

  const headerName = reportOnly ? 'Content-Security-Policy-Report-Only' : 'Content-Security-Policy';
  const escapedPolicy = cspPolicy.replace(/"/g, '&quot;');
  const metaTag = `  <meta http-equiv="${headerName}" content="${escapedPolicy}">`;

  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      injectCspMeta(fullPath, cspPolicy, reportOnly, nonce);
    } else if (entry.name.endsWith('.html')) {
      let content = readFileSync(fullPath, 'utf-8');
      // Check if already injected (by header name, not full policy — policy may change)
      if (!content.includes(`http-equiv="${headerName}"`)) {
        content = insertAfterHead(content, metaTag);
        writeFileSync(fullPath, content, 'utf-8');
      }
    }
  }
}

/**
 * Walk all HTML files in dist and rewrite legacy island import paths.
 *
 * Before: import('/app/islands/code-block.ts')
 * After:  import('/client/islands/island-code-block-abc123.js')
 *
 * NOTE: With the v0.5.0 upgrade architecture, island imports live in the
 * Vite-built client entry, not inline scripts. This function catches any
 * residual source path references left by older generated HTML fixtures.
 */
export function rewriteHtmlFiles(
  dir: string,
  islandChunkMap: Record<string, string>,
): void {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      rewriteHtmlFiles(fullPath, islandChunkMap);
    } else if (entry.name.endsWith('.html')) {
      let content = readFileSync(fullPath, 'utf-8');
      let modified = false;

      // Rewrite legacy island import paths
      for (const [tagName, chunkPath] of Object.entries(islandChunkMap)) {
        const sourcePattern = `import('/app/islands/${tagName}.ts')`;
        if (content.includes(sourcePattern)) {
          content = content.replaceAll(sourcePattern, `import('${chunkPath}')`);
          modified = true;
        }
        const sourcePattern2 = `import('app/islands/${tagName}.ts')`;
        if (content.includes(sourcePattern2)) {
          content = content.replaceAll(sourcePattern2, `import('${chunkPath}')`);
          modified = true;
        }
      }

      if (modified) {
        writeFileSync(fullPath, content, 'utf-8');
      }
    }
  }
}
