/**
 * @openelement/content - Blog data loader
 *
 * Pure function for loading blog data from the file system.
 * Zero module-level state. Zero side effects beyond reading files.
 *
 * ADR 0018: Replaces the old stateful initBlogData() + getPosts() pattern.
 * Route components import data from @openelement/generated/blog-data instead.
 * This module is only called by the virtual module plugin's load() hook.
 */

import type { BlogPost, LessBlogOptions } from './types.ts';
import { generateBlogRoutes } from './routes.ts';

/**
 * Pure function: load blog data from file system.
 * No module-level state. No side effects beyond reading files.
 * Can be called from any runtime context.
 *
 * This replaces the stateful initBlogData() + getPosts() pattern.
 * For virtual module consumers, use @openelement/generated/blog-data instead.
 */
export async function loadBlogData(options?: LessBlogOptions): Promise<{
  posts: BlogPost[];
  basePath: string;
}> {
  const routes = await generateBlogRoutes(options);
  return {
    posts: routes.posts,
    basePath: routes.basePath,
  };
}

/**
 * Generate TypeScript module source code for blog data.
 * The output is a self-contained .ts file that exports posts,
 * getPostBySlug(), and getBlogOptions().
 *
 * SOP-001: Virtual Modules Removal — replaces @openelement/generated/blog-data.
 *
 * @param posts - Array of parsed blog posts
 * @returns TypeScript module source string
 */
export function writeBlogDataModule(posts: BlogPost[]): string {
  return [
    '// Auto-generated by @openelement/content — do not edit',
    '// deno-lint-ignore no-explicit-any',
    `export const posts: any[] = ${JSON.stringify(posts, null, 2)};`,
    '',
    '// deno-lint-ignore no-explicit-any',
    'export function getPostBySlug(slug: string): any {',
    '  // deno-lint-ignore no-explicit-any',
    '  return posts.find((p: any) => p.slug === slug);',
    '}',
    '',
    'export function getBlogOptions() {',
    '  return { contentDir: "content/blog", basePath: "/blog" };',
    '}',
  ].join('\n') + '\n';
}
