/**
 * @lessjs/content/nav - Navigation data module writer
 *
 * Generates a TypeScript module string from NavData that can be
 * written to a file and imported directly by route components.
 * Replaces the virtual:less-nav virtual module pattern.
 *
 * SOP-001: Virtual Modules Removal
 */

import type { NavData } from './scanner.js';

/**
 * Generate TypeScript module source code for navigation data.
 * The output is a self-contained .ts file that exports headerNav
 * and navSections directly.
 *
 * @param data - Aggregated navigation data from scanNavData()
 * @returns TypeScript module source string
 */
export function writeNavModule(data: NavData): string {
  return [
    '// Auto-generated by @lessjs/content — do not edit',
    `export const headerNav = ${JSON.stringify(data.headerNav, null, 2)};`,
    `export const navSections = ${JSON.stringify(data.navSections, null, 2)};`,
  ].join('\n') + '\n';
}
