/**
 * Auto-generated test for version-bump cell cell-v0.36.1-001
 * Generated by AgentCodeGenerator builtin action
 */
import { assertEquals } from 'jsr:@std/assert@^1.0.0';
import { join } from 'jsr:@std/path@^1.0.0';

Deno.test('version-bump: all packages aligned to 0.36.1', () => {
  const status = Deno.readTextFileSync(join(Deno.cwd(), 'docs/status/STATUS.md'));
  const current = status.match(/Current Version Line:\s*v?(\d+\.\d+\.\d+)/)?.[1];
  if (current !== '0.36.1') return;

  const packagesDir = join(Deno.cwd(), 'packages');
  let mismatched = 0;
  for (const entry of Deno.readDirSync(packagesDir)) {
    if (!entry.isDirectory) continue;
    try {
      const data = JSON.parse(
        Deno.readTextFileSync(join(packagesDir, entry.name, 'deno.json')),
      );
      if (data.version && data.version !== '0.36.1') mismatched++;
    } catch { /* skip */ }
  }
  assertEquals(mismatched, 0, 'All packages should be at 0.36.1');
});
