/**
 * @lessjs/create - cli.ts tests (Deno)
 *
 * Tests template correctness by reading the source directly.
 * We do NOT call main() because it invokes Deno.exit() which
 * kills the Deno test process.
 */
import { assert, assertEquals, assertExists, assertFalse } from 'jsr:@std/assert@^1.0.0';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..', '..', '..');
const cliSource = readFileSync(join(__dirname, '..', 'cli.ts'), 'utf-8');

function vitePath(path: string): string {
  return path.replace(/\\/g, '/');
}

// Extract each template by splitting on known keys
function extractTemplate(key: string): string {
  const marker = `'${key}': \``;
  const startIdx = cliSource.indexOf(marker);
  if (startIdx === -1) throw new Error(`Template '${key}' not found`);

  const contentStart = startIdx + marker.length;
  let depth = 1;
  let i = contentStart;

  while (i < cliSource.length && depth > 0) {
    if (cliSource[i] === '`') {
      // Check if escaped
      const backslashCount = countTrailingBackslashes(cliSource, i - 1);
      if (backslashCount % 2 === 0) {
        depth--;
        if (depth === 0) break;
      }
    }
    i++;
  }

  return cliSource.slice(contentStart, i);
}

function countTrailingBackslashes(s: string, pos: number): number {
  let count = 0;
  while (pos >= 0 && s[pos] === '\\') {
    count++;
    pos--;
  }
  return count;
}

// --- Scaffold Tests ---

Deno.test('create-less: deno.json has all required tasks', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));

  assertExists(denoJson.tasks['dev'], 'Missing dev task');
  assertExists(denoJson.tasks['build'], 'Missing build task');
  assertExists(denoJson.tasks['build:client'], 'Missing build:client task');
  assertExists(denoJson.tasks['build:ssg'], 'Missing build:ssg task');
  assertExists(denoJson.tasks['preview'], 'Missing preview task');
});

Deno.test('create-less: gitignore hides generated build artifacts', () => {
  const gitignore = extractTemplate('.gitignore');
  // ADR 0013: .less/ removed — no longer generated by the framework
  assertFalse(gitignore.includes('.less/'));
  assert(gitignore.includes('dist/'));
  assert(gitignore.includes('node_modules/'));
});

Deno.test('create-less: deno.json build:client uses @lessjs/adapter-vite', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  assert(denoJson.tasks['build:client'].includes('@lessjs/adapter-vite'));
});

Deno.test('create-less: deno.json build:ssg uses @lessjs/adapter-vite', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  assert(denoJson.tasks['build:ssg'].includes('@lessjs/adapter-vite'));
});

Deno.test('create-less: deno.json maps Lit and package imports explicitly', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  assertEquals(denoJson.imports.lit, 'npm:lit@^3.2.0');
  assertEquals(denoJson.imports['@lit/reactive-element'], 'npm:@lit/reactive-element@^2');
  assertEquals(denoJson.imports['lit-element'], 'npm:lit-element@^4');
  assertEquals(denoJson.imports['lit-html'], 'npm:lit-html@^3');
  assertEquals(denoJson.imports.vite, 'npm:vite@8.0.10');
  // @lit-labs/ssr-dom-shim required by @lit/reactive-element in Vite SSR
  assertEquals(denoJson.imports['@lit-labs/ssr-dom-shim'], 'npm:@lit-labs/ssr-dom-shim@^1.5.0');
  assertEquals(denoJson.imports['@lessjs/app'], 'jsr:@lessjs/app@^${v.app}');
  assertEquals(denoJson.imports['@lessjs/adapter-lit'], 'jsr:@lessjs/adapter-lit@^${v.adapterLit}');
  assertEquals(denoJson.imports['@lessjs/core'], 'jsr:@lessjs/core@^${v.core}');
  assertEquals(
    denoJson.imports['@lessjs/core/navigation'],
    'jsr:@lessjs/core@^${v.core}/navigation',
  );
  assertEquals(denoJson.imports['@lessjs/ui'], 'jsr:@lessjs/ui@^${v.ui}');
  assertEquals(
    denoJson.imports['@lessjs/ui/tokens/colors'],
    'jsr:@lessjs/ui@^${v.ui}/tokens/colors',
  );
  assertEquals(
    denoJson.imports['@lessjs/ui/tokens/color-values'],
    'jsr:@lessjs/ui@^${v.ui}/tokens/color-values',
  );
  assertEquals(denoJson.imports['@lessjs/ui/'], 'jsr:@lessjs/ui@^${v.ui}/');
  assertEquals(denoJson.nodeModulesDir, 'auto');
});

Deno.test('create-less: deno.json build uses the one-command LessJS build', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  assertEquals(
    denoJson.tasks['build'],
    'deno run --config deno.json -A jsr:@lessjs/adapter-vite@^${v.adapterVite}/cli/build',
  );
  assertExists(denoJson.tasks['build:ssr']);
  assertExists(denoJson.tasks['build:client']);
  assertExists(denoJson.tasks['build:ssg']);
});

Deno.test('create-less: refuses path escape and existing target before writing', () => {
  assert(cliSource.includes('relative(cwd, targetDir)'));
  assert(cliSource.includes('Refusing to create project outside the current directory'));
  assert(cliSource.includes('Directory "${name}" already exists.'));
  assert(cliSource.includes('Deno.stat(targetDir)'));
});

Deno.test('create-less: vite.config.ts imports lessjs plugin', () => {
  const viteConfig = extractTemplate('vite.config.ts');
  assert(viteConfig.includes("import { lessjs } from '@lessjs/app'"));
  assert(viteConfig.includes('lessjs({'));
});

Deno.test('create-less: vite.config.ts includes packageIslands config', () => {
  const viteConfig = extractTemplate('vite.config.ts');
  assert(viteConfig.includes('@lessjs/ui'));
  assert(viteConfig.includes('lessUiAliases'));
  assert(viteConfig.includes('https://jsr.io/@lessjs/ui/${v.ui}'));
});

Deno.test('create-less: route index imports Lit directly', () => {
  const routeIndex = extractTemplate('app/routes/index.ts');
  assert(routeIndex.includes("from 'lit'"));
  assertEquals(routeIndex.includes('@lessjs/core'), false);
  assert(routeIndex.includes('LitElement'));
  assert(routeIndex.includes('static override styles'));
  assert(routeIndex.includes('override render()'));
  assert(routeIndex.includes('tagName'));
});

Deno.test('create-less: island counter imports Lit directly and self-registers', () => {
  const islandCounter = extractTemplate('app/islands/my-counter.ts');
  assert(islandCounter.includes("from 'lit'"));
  assertEquals(islandCounter.includes('@lessjs/core'), false);
  assert(islandCounter.includes('LitElement'));
  assert(islandCounter.includes("tagName = 'my-counter'"));
  assert(islandCounter.includes('declare count: number'));
  assert(islandCounter.includes('customElements.define(tagName, MyCounter)'));
});

Deno.test('create-less: generated project builds through the one-command pipeline', async () => {
  const tmpRoot = Deno.makeTempDirSync({ prefix: 'less-create-' });
  const projectName = 'sample-app';

  try {
    const create = new Deno.Command(Deno.execPath(), {
      args: ['run', '-A', join(repoRoot, 'packages', 'create', 'cli.ts'), projectName],
      cwd: tmpRoot,
      stdout: 'piped',
      stderr: 'piped',
    });
    const createResult = await create.output();
    assertEquals(createResult.code, 0, new TextDecoder().decode(createResult.stderr));

    const appDir = join(tmpRoot, projectName);
    const denoJsonPath = join(appDir, 'deno.json');
    const denoJson = JSON.parse(readFileSync(denoJsonPath, 'utf-8'));
    denoJson.imports['@lessjs/app'] = pathToFileURL(
      join(repoRoot, 'packages', 'app', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@lessjs/core'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@lessjs/core/logger'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'logger.ts'),
    ).href;
    denoJson.imports['@lessjs/core/navigation'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'navigation.ts'),
    ).href;
    denoJson.imports['@lessjs/adapter-vite/build-context'] = pathToFileURL(
      join(repoRoot, 'packages', 'adapter-vite', 'src', 'build-context.ts'),
    ).href;
    denoJson.imports['@lessjs/adapter-vite'] = pathToFileURL(
      join(repoRoot, 'packages', 'adapter-vite', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@lessjs/content'] = pathToFileURL(
      join(repoRoot, 'packages', 'content', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@lessjs/i18n'] = pathToFileURL(
      join(repoRoot, 'packages', 'i18n', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@lessjs/adapter-lit'] = pathToFileURL(
      join(repoRoot, 'packages', 'adapter-lit', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@lessjs/adapter-lit/ssr'] = pathToFileURL(
      join(repoRoot, 'packages', 'adapter-lit', 'src', 'ssr.ts'),
    ).href;
    denoJson.imports['@lessjs/ui'] = pathToFileURL(
      join(repoRoot, 'packages', 'ui', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@lessjs/ui/'] = pathToFileURL(
      join(repoRoot, 'packages', 'ui', 'src') + sep,
    ).href;
    denoJson.imports['vite'] = 'npm:vite@8.0.10';
    denoJson.imports['hono'] = 'npm:hono@^4';
    denoJson.imports['@hono/vite-dev-server'] = 'npm:@hono/vite-dev-server@^0.25.3';
    denoJson.tasks.build = `deno run -A ${
      join(repoRoot, 'packages', 'adapter-vite', 'src', 'cli', 'build.ts')
    }`;
    writeFileSync(denoJsonPath, JSON.stringify(denoJson, null, 2));

    const uiSrc = join(repoRoot, 'packages', 'ui', 'src');
    const aliases = [
      {
        find: '@lessjs/adapter-vite/build-context',
        replacement: vitePath(
          join(repoRoot, 'packages', 'adapter-vite', 'src', 'build-context.ts'),
        ),
      },
      {
        find: '@lessjs/adapter-vite',
        replacement: vitePath(join(repoRoot, 'packages', 'adapter-vite', 'src', 'index.ts')),
      },
      {
        find: '@lessjs/core/logger',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'logger.ts')),
      },
      {
        find: '@lessjs/core/navigation',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'navigation.ts')),
      },
      {
        find: '@lessjs/core',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'index.ts')),
      },
      {
        find: '@lessjs/adapter-lit/ssr',
        replacement: vitePath(join(repoRoot, 'packages', 'adapter-lit', 'src', 'ssr.ts')),
      },
      {
        find: '@lessjs/adapter-lit',
        replacement: vitePath(join(repoRoot, 'packages', 'adapter-lit', 'src', 'index.ts')),
      },
      {
        find: '@lessjs/ui/design-tokens',
        replacement: vitePath(join(uiSrc, 'design-tokens.ts')),
      },
      {
        find: '@lessjs/ui/tokens/colors',
        replacement: vitePath(join(uiSrc, 'tokens', 'colors.ts')),
      },
      {
        find: '@lessjs/ui/tokens/color-values',
        replacement: vitePath(join(uiSrc, 'tokens', 'color-values.ts')),
      },
      {
        find: '@lessjs/ui/less-button',
        replacement: vitePath(join(uiSrc, 'less-button.ts')),
      },
      {
        find: '@lessjs/ui/less-card',
        replacement: vitePath(join(uiSrc, 'less-card.ts')),
      },
      {
        find: '@lessjs/ui/less-input',
        replacement: vitePath(join(uiSrc, 'less-input.ts')),
      },
      {
        find: '@lessjs/ui/less-code-block',
        replacement: vitePath(join(uiSrc, 'less-code-block.ts')),
      },
      {
        find: '@lessjs/ui/less-layout',
        replacement: vitePath(join(uiSrc, 'less-layout.ts')),
      },
      {
        find: '@lessjs/ui/less-theme-toggle',
        replacement: vitePath(join(uiSrc, 'less-theme-toggle.ts')),
      },
      {
        find: '@lessjs/ui/less-hero-ping',
        replacement: vitePath(join(uiSrc, 'less-hero-ping.ts')),
      },
      {
        find: '@lessjs/ui/less-dialog',
        replacement: vitePath(join(uiSrc, 'less-dialog.ts')),
      },
      // Parent @lessjs/ui alias MUST come after all @lessjs/ui/* subpath aliases
      // (Vite matches first-hit for string aliases — parent before subpath causes
      // "Not a directory (os error 20)" for subpath imports like @lessjs/ui/less-dialog)
      {
        find: '@lessjs/ui',
        replacement: vitePath(join(uiSrc, 'index.ts')),
      },
      // @lessjs/app must resolve to local source
      {
        find: '@lessjs/app',
        replacement: vitePath(join(repoRoot, 'packages', 'app', 'src', 'index.ts')),
      },
    ];
    const viteConfigPath = join(appDir, 'vite.config.ts');
    let viteConfig = readFileSync(viteConfigPath, 'utf-8');
    viteConfig = viteConfig.replace(
      "import { lessjs } from '@lessjs/app';",
      `import { less } from ${
        JSON.stringify(
          pathToFileURL(join(repoRoot, 'packages', 'adapter-vite', 'src', 'index.ts')).href,
        )
      };`,
    );
    viteConfig = viteConfig.replace(
      'lessjs({',
      'less({',
    );
    viteConfig = viteConfig.replace(
      "import { lessRootColorCSS } from '@lessjs/ui/tokens/colors';",
      `import { lessRootColorCSS } from ${
        JSON.stringify(
          pathToFileURL(join(uiSrc, 'tokens', 'colors.ts')).href,
        )
      };`,
    );
    viteConfig = viteConfig.replace(
      "packageIslands: ['@lessjs/ui'],",
      `packageIslands: [${JSON.stringify(pathToFileURL(join(uiSrc, 'index.ts')).href)}],`,
    );
    viteConfig = viteConfig.replace(
      'alias: lessUiAliases',
      `alias: ${JSON.stringify(aliases, null, 4)}`,
    );
    writeFileSync(viteConfigPath, viteConfig);

    Deno.symlinkSync(join(repoRoot, 'node_modules'), join(appDir, 'node_modules'), {
      type: 'dir',
    });

    const build = new Deno.Command(Deno.execPath(), {
      args: ['task', 'build'],
      cwd: appDir,
      stdout: 'piped',
      stderr: 'piped',
    });
    const buildResult = await build.output();
    const stderr = new TextDecoder().decode(buildResult.stderr);
    const stdout = new TextDecoder().decode(buildResult.stdout);
    assertEquals(buildResult.code, 0, `${stdout}\n${stderr}`);

    const indexHtmlPath = join(appDir, 'dist', 'index.html');
    assertEquals(existsSync(indexHtmlPath), true);
    assertEquals(existsSync(join(appDir, 'dist', 'client', '.vite', 'manifest.json')), true);
    const indexHtml = readFileSync(indexHtmlPath, 'utf-8');
    if (!indexHtml.includes('Hello from LessJS')) {
      console.error('index.html length:', indexHtml.length);
      console.error('contains shadowrootmode:', indexHtml.includes('shadowrootmode'));
      console.error('contains template:', indexHtml.includes('<template'));
      console.error('contains LessJS ERROR:', indexHtml.includes('LessJS ERROR'));
      console.error('last 300 chars:', indexHtml.substring(indexHtml.length - 300));
    }
    assertEquals(indexHtml.includes('Hello from LessJS'), true);
    assertEquals(indexHtml.includes('[object Object]'), false);
  } finally {
    rmSync(tmpRoot, { recursive: true, force: true });
  }
});

Deno.test('create-less: --help flag prints usage info', async () => {
  const help = new Deno.Command(Deno.execPath(), {
    args: ['run', '-A', join(__dirname, '..', 'cli.ts'), '--help'],
    cwd: Deno.makeTempDirSync({ prefix: 'less-help-' }),
    stdout: 'piped',
    stderr: 'piped',
  });
  const result = await help.output();
  const output = new TextDecoder().decode(result.stdout);
  // Should print usage/help info without error
  assertEquals(result.code, 0);
  assert(output.includes('Usage') || output.includes('usage') || output.includes('--help'));
});

Deno.test('create-less: rejects project name with spaces', async () => {
  const tmpRoot = Deno.makeTempDirSync({ prefix: 'less-create-' });
  try {
    const create = new Deno.Command(Deno.execPath(), {
      args: ['run', '-A', join(__dirname, '..', 'cli.ts'), 'my app'],
      cwd: tmpRoot,
      stdout: 'piped',
      stderr: 'piped',
    });
    const result = await create.output();
    const stderr = new TextDecoder().decode(result.stderr);
    const stdout = new TextDecoder().decode(result.stdout);
    // Should fail with an error code and mention the invalid name
    // (exact exit code depends on how the CLI validates input)
    assertExists(
      result.code !== 0 || stderr.includes('my app') || stdout.includes('my app'),
    );
  } finally {
    rmSync(tmpRoot, { recursive: true, force: true });
  }
});
