/**
 * @openelement/create - cli.ts tests (Deno)
 *
 * Tests template correctness by reading the source directly.
 * We do NOT call main() because it invokes Deno.exit() which
 * kills the Deno test process.
 */
import { assert, assertEquals, assertExists, assertFalse } from 'jsr:@std/assert@^1.0.0';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..', '..', '..');
const cliSource = readFileSync(join(__dirname, '..', 'cli.ts'), 'utf-8');

function vitePath(path: string): string {
  return path.replace(/\\/g, '/');
}

// Extract each template by splitting on known keys
function extractTemplate(key: string): string {
  const marker = `'${key}':`;
  const startIdx = cliSource.indexOf(marker);
  if (startIdx === -1) throw new Error(`Template '${key}' not found`);

  const firstBacktick = cliSource.indexOf('`', startIdx + marker.length);
  if (firstBacktick === -1) throw new Error(`Template '${key}' has no string body`);

  const contentStart = firstBacktick + 1;
  let depth = 1;
  let i = contentStart;

  while (i < cliSource.length && depth > 0) {
    if (cliSource[i] === '`') {
      // Check if escaped
      const backslashCount = countTrailingBackslashes(cliSource, i - 1);
      if (backslashCount % 2 === 0) {
        depth--;
        if (depth === 0) break;
      }
    }
    i++;
  }

  return cliSource.slice(contentStart, i);
}

function countTrailingBackslashes(s: string, pos: number): number {
  let count = 0;
  while (pos >= 0 && s[pos] === '\\') {
    count++;
    pos--;
  }
  return count;
}

// --- Scaffold Tests ---

Deno.test('create-open: deno.json has all required tasks', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));

  assertExists(denoJson.tasks['dev'], 'Missing dev task');
  assertExists(denoJson.tasks['build'], 'Missing build task');
  assertExists(denoJson.tasks['build:client'], 'Missing build:client task');
  assertExists(denoJson.tasks['build:ssg'], 'Missing build:ssg task');
  assertExists(denoJson.tasks['preview'], 'Missing preview task');
});

Deno.test('create-open: gitignore hides generated build artifacts', () => {
  const gitignore = extractTemplate('.gitignore');
  // ADR 0013: .openElement/ removed; it is no longer generated by the framework.
  assertFalse(gitignore.includes('.openElement/'));
  assert(gitignore.includes('dist/'));
  assert(gitignore.includes('node_modules/'));
});

Deno.test('create-open: deno.json build:client uses @openelement/adapter-vite', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  assert(denoJson.tasks['build:client'].includes('@openelement/adapter-vite'));
});

Deno.test('create-open: deno.json build:ssg uses @openelement/adapter-vite', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  assert(denoJson.tasks['build:ssg'].includes('@openelement/adapter-vite'));
});

Deno.test('create-open: deno.json maps openElement package imports (v0.23 runtime facade)', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  // v0.23 SOP-003: Keep generated import map minimal while listing direct authoring/config imports.
  const importKeys = Object.keys(denoJson.imports);
  assertEquals(
    importKeys.length,
    8,
    `Expected 8 imports, got ${importKeys.length}: ${importKeys.join(', ')}`,
  );
  // v0.23.6: external SSR dependencies declared in consumer import map
  assertEquals(denoJson.imports['alien-signals'], 'npm:alien-signals@^3.2.0');
  assertEquals(denoJson.imports['@deno/vite-plugin'], 'npm:@deno/vite-plugin');
  assertEquals(denoJson.imports['entities'], 'npm:entities@^4.5.0');
  assertEquals(denoJson.imports['hono'], 'npm:hono@4.12.23');
  assertEquals(denoJson.imports['@openelement/app'], 'jsr:@openelement/app@^${v.app}');
  assertEquals(denoJson.imports['@openelement/runtime'], 'jsr:@openelement/runtime@^${v.runtime}');
  assertEquals(denoJson.imports['@openelement/ui'], 'jsr:@openelement/ui@^${v.ui}');
  assertEquals(denoJson.imports['vite'], 'npm:vite@8.0.10');
  assertEquals(denoJson.nodeModulesDir, 'auto');
});

Deno.test('create-open: deno.json maps vite because vite.config.ts imports it directly', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  const viteConfig = extractTemplate('vite.config.ts');
  assert(viteConfig.includes("from 'vite'"));
  assertEquals(denoJson.imports['vite'], 'npm:vite@8.0.10');
});

Deno.test('create-open: deno.json build uses the one-command openElement build', () => {
  const denoJson = JSON.parse(extractTemplate('deno.json'));
  assertEquals(
    denoJson.tasks['build'],
    'deno run --config deno.json -A jsr:@openelement/adapter-vite@^${v.adapterVite}/cli/build',
  );
  assertExists(denoJson.tasks['build:ssr']);
  assertExists(denoJson.tasks['build:client']);
  assertExists(denoJson.tasks['build:ssg']);
});

Deno.test('create-open: refuses path escape and existing target before writing', () => {
  assert(cliSource.includes('relative(cwd, targetDir)'));
  assert(cliSource.includes('Refusing to create project outside the current directory'));
  assert(cliSource.includes('Directory "${name}" already exists.'));
  assert(cliSource.includes('Deno.stat(targetDir)'));
});

Deno.test('create-open: vite.config.ts imports openElement plugin', () => {
  const viteConfig = extractTemplate('vite.config.ts');
  assert(viteConfig.includes("import { openElement } from '@openelement/app'"));
  assert(viteConfig.includes('openElement({'));
});

Deno.test('create-open: vite.config.ts includes packageIslands config', () => {
  const viteConfig = extractTemplate('vite.config.ts');
  assert(viteConfig.includes('@openelement/ui'));
  assert(viteConfig.includes("packageIslands: ['@openelement/ui']"));
  // v0.21.6: Hardcoded JSR URL aliases removed — plugin auto-generates them
  assertFalse(viteConfig.includes('lessUiAliases'));
  assertFalse(viteConfig.includes('https://jsr.io/@openelement/ui/'));
});

Deno.test('create-open: vite.config.ts includes virtual-passthrough resolve plugin (SOP-015)', () => {
  const viteConfig = extractTemplate('vite.config.ts');
  assert(viteConfig.includes('virtual-passthrough'));
  assert(viteConfig.includes("return '\\0' + id"));
  assert(viteConfig.includes("from '@deno/vite-plugin'"));
});

Deno.test('create-open: route index imports DsdElement (v0.20 Ocean-Island)', () => {
  const routeIndex = extractTemplate('app/routes/index.tsx');
  assert(routeIndex.includes('DsdElement'));
  assert(routeIndex.includes("from '@openelement/runtime'"));
  assert(routeIndex.includes('@jsxImportSource @openelement/core'));
  assert(routeIndex.includes('StyleSheet'));
  assert(routeIndex.includes('static override styles'));
  assert(routeIndex.includes('override render()'));
  assert(routeIndex.includes('<h1>Hello from openElement!</h1>'));
  assertEquals(routeIndex.includes('return `'), false);
  assert(routeIndex.includes('tagName'));
  // Verify no Lit dependency in Ocean template
  assertEquals(routeIndex.includes("from 'lit'"), false);
  assertEquals(routeIndex.includes('LitElement'), false);
});

Deno.test('create-open: island counter uses JSX + static props (v0.24)', () => {
  const islandCounter = extractTemplate('app/islands/my-counter.tsx');
  assert(islandCounter.includes('DsdElement'));
  assert(islandCounter.includes("from '@openelement/runtime'"));
  assert(islandCounter.includes("tagName = 'my-counter'"));
  assert(islandCounter.includes('static props'));
  assert(islandCounter.includes('@jsxImportSource @openelement/core'));
  assert(islandCounter.includes('customElements.define'));
  // Verify no Lit dependency in template
  assertEquals(islandCounter.includes("from 'lit'"), false);
  assertEquals(islandCounter.includes('LitElement'), false);
});

Deno.test('create-open: generated project builds through the one-command pipeline', async () => {
  const tmpRoot = Deno.makeTempDirSync({ prefix: 'open-create-' });
  const projectName = 'sample-app';

  try {
    const create = new Deno.Command(Deno.execPath(), {
      args: ['run', '-A', join(repoRoot, 'packages', 'create', 'cli.ts'), projectName],
      cwd: tmpRoot,
      stdout: 'piped',
      stderr: 'piped',
    });
    const createResult = await create.output();
    assertEquals(createResult.code, 0, new TextDecoder().decode(createResult.stderr));

    const appDir = join(tmpRoot, projectName);
    const denoJsonPath = join(appDir, 'deno.json');
    const denoJson = JSON.parse(readFileSync(denoJsonPath, 'utf-8'));
    denoJson.imports['@openelement/app'] = pathToFileURL(
      join(repoRoot, 'packages', 'app', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/core'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/core/logger'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'logger.ts'),
    ).href;
    denoJson.imports['@openelement/core/render-ir'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'render-ir.ts'),
    ).href;
    denoJson.imports['@openelement/core/jsx-runtime'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'jsx-runtime.ts'),
    ).href;
    denoJson.imports['@openelement/core/jsx-dev-runtime'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'jsx-runtime.ts'),
    ).href;
    denoJson.imports['@openelement/adapter-vite'] = pathToFileURL(
      join(repoRoot, 'packages', 'adapter-vite', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/core'] = pathToFileURL(
      join(repoRoot, 'packages', 'core', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/signals'] = pathToFileURL(
      join(repoRoot, 'packages', 'signals', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/signals/framework'] = pathToFileURL(
      join(repoRoot, 'packages', 'signals', 'src', 'framework.ts'),
    ).href;
    denoJson.imports['@openelement/runtime'] = pathToFileURL(
      join(repoRoot, 'packages', 'runtime', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/style-sheet'] = pathToFileURL(
      join(repoRoot, 'packages', 'style-sheet', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/content'] = pathToFileURL(
      join(repoRoot, 'packages', 'content', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/i18n'] = pathToFileURL(
      join(repoRoot, 'packages', 'i18n', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/adapter-lit'] = pathToFileURL(
      join(repoRoot, 'packages', 'adapter-lit', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/adapter-lit/ssr'] = pathToFileURL(
      join(repoRoot, 'packages', 'adapter-lit', 'src', 'ssr.ts'),
    ).href;
    denoJson.imports['@openelement/ui'] = pathToFileURL(
      join(repoRoot, 'packages', 'ui', 'src', 'index.ts'),
    ).href;
    denoJson.imports['@openelement/ui/'] = pathToFileURL(
      join(repoRoot, 'packages', 'ui', 'src') + sep,
    ).href;
    denoJson.imports['lit'] = 'npm:lit@^3.2.0';
    denoJson.imports['vite'] = 'npm:vite@8.0.10';
    denoJson.imports['@deno/vite-plugin'] = 'npm:@deno/vite-plugin';
    denoJson.imports['hono'] = 'npm:hono@4.12.23';
    denoJson.imports['@hono/vite-dev-server'] = 'npm:@hono/vite-dev-server@^0.25.3';
    denoJson.imports['entities'] = 'npm:entities@^4';
    denoJson.imports['entities/'] = 'npm:entities@^4/';
    denoJson.tasks.build = `deno run -A ${
      join(repoRoot, 'packages', 'adapter-vite', 'src', 'cli', 'build.ts')
    }`;
    // Remove sub-tasks that Vite 8 configLoader:'native' may trigger independently.
    // These would run without our import map plugin + alias filtering, causing
    // the original @openelement/ui/<subpath> ENOTDIR error.
    delete denoJson.tasks['build:ssr'];
    delete denoJson.tasks['build:client'];
    delete denoJson.tasks['build:ssg'];
    writeFileSync(denoJsonPath, JSON.stringify(denoJson, null, 2));

    const uiSrc = join(repoRoot, 'packages', 'ui', 'src');
    const signalsSrc = join(repoRoot, 'packages', 'signals', 'src');
    const aliases = [
      {
        find: '@openelement/adapter-vite',
        replacement: vitePath(join(repoRoot, 'packages', 'adapter-vite', 'src', 'index.ts')),
      },
      {
        find: '@openelement/core/logger',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'logger.ts')),
      },
      {
        find: '@openelement/core/render-ir',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'render-ir.ts')),
      },
      {
        find: '@openelement/core/jsx-runtime',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'jsx-runtime.ts')),
      },
      {
        find: '@openelement/core/jsx-dev-runtime',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'jsx-runtime.ts')),
      },
      {
        find: '@openelement/core',
        replacement: vitePath(join(repoRoot, 'packages', 'core', 'src', 'index.ts')),
      },
      {
        find: '@openelement/signals/framework',
        replacement: vitePath(join(signalsSrc, 'framework.ts')),
      },
      {
        find: '@openelement/runtime',
        replacement: vitePath(join(repoRoot, 'packages', 'runtime', 'src', 'index.ts')),
      },
      {
        find: '@openelement/style-sheet',
        replacement: vitePath(join(repoRoot, 'packages', 'style-sheet', 'src', 'index.ts')),
      },
      {
        find: '@openelement/adapter-lit/ssr',
        replacement: vitePath(join(repoRoot, 'packages', 'adapter-lit', 'src', 'ssr.ts')),
      },
      {
        find: '@openelement/adapter-lit',
        replacement: vitePath(join(repoRoot, 'packages', 'adapter-lit', 'src', 'index.ts')),
      },
      {
        find: '@openelement/ui/open-props-tokens',
        replacement: vitePath(join(uiSrc, 'open-props-tokens.ts')),
      },
      {
        find: '@openelement/ui/open-button',
        replacement: vitePath(join(uiSrc, 'open-button.tsx')),
      },
      {
        find: '@openelement/ui/open-card',
        replacement: vitePath(join(uiSrc, 'open-card.tsx')),
      },
      {
        find: '@openelement/ui/open-input',
        replacement: vitePath(join(uiSrc, 'open-input.tsx')),
      },
      {
        find: '@openelement/ui/open-code-block',
        replacement: vitePath(join(uiSrc, 'open-code-block.tsx')),
      },
      {
        find: '@openelement/ui/open-callout',
        replacement: vitePath(join(uiSrc, 'open-callout.tsx')),
      },
      {
        find: '@openelement/ui/open-layout',
        replacement: vitePath(join(uiSrc, 'open-layout.tsx')),
      },
      {
        find: '@openelement/ui/open-step-card',
        replacement: vitePath(join(uiSrc, 'open-step-card.tsx')),
      },
      {
        find: '@openelement/ui/open-theme-toggle',
        replacement: vitePath(join(uiSrc, 'open-theme-toggle.tsx')),
      },
      {
        find: '@openelement/ui/open-hero-ping',
        replacement: vitePath(join(uiSrc, 'open-hero-ping.tsx')),
      },
      {
        find: '@openelement/ui/open-dialog',
        replacement: vitePath(join(uiSrc, 'open-dialog.tsx')),
      },
      // Parent @openelement/ui alias MUST come after all @openelement/ui/* subpath aliases.
      // Point to the source directory (not index.ts) so Rolldown can resolve
      // subpath imports like @openelement/ui/open-callout without ENOTDIR.
      {
        find: '@openelement/ui',
        replacement: vitePath(uiSrc),
      },
      // @openelement/app must resolve to local source
      {
        find: '@openelement/app',
        replacement: vitePath(join(repoRoot, 'packages', 'app', 'src', 'index.ts')),
      },
    ];
    const viteConfigPath = join(appDir, 'vite.config.ts');
    let viteConfig = readFileSync(viteConfigPath, 'utf-8');
    viteConfig = viteConfig.replace(
      "import { openPropsTokenSheet } from '@openelement/ui/open-props-tokens';",
      `import { openPropsTokenSheet } from ${
        JSON.stringify(
          pathToFileURL(join(uiSrc, 'open-props-tokens.ts')).href,
        )
      };`,
    );
    viteConfig = viteConfig.replace(
      "packageIslands: ['@openelement/ui'],",
      `packageIslands: [${JSON.stringify(pathToFileURL(join(uiSrc, 'index.ts')).href)}],`,
    );
    // v0.21.6: Template no longer has hardcoded aliases.
    // Inject resolve.alias for local workspace testing.
    viteConfig = viteConfig.replace(
      'plugins: [',
      `resolve: { alias: ${JSON.stringify(aliases, null, 4)} },\n  plugins: [`,
    );
    writeFileSync(viteConfigPath, viteConfig);

    Deno.symlinkSync(join(repoRoot, 'node_modules'), join(appDir, 'node_modules'), {
      type: 'dir',
    });

    const build = new Deno.Command(Deno.execPath(), {
      args: ['task', 'build'],
      cwd: appDir,
      stdout: 'piped',
      stderr: 'piped',
    });
    const buildResult = await build.output();
    const stderr = new TextDecoder().decode(buildResult.stderr);
    const stdout = new TextDecoder().decode(buildResult.stdout);
    assertEquals(buildResult.code, 0, `${stdout}\n${stderr}`);

    const indexHtmlPath = join(appDir, 'dist', 'index.html');
    assertEquals(existsSync(indexHtmlPath), true);
    assertEquals(existsSync(join(appDir, 'dist', 'client', '.vite', 'manifest.json')), true);
    const indexHtml = readFileSync(indexHtmlPath, 'utf-8');
    if (!indexHtml.includes('Hello from openElement')) {
      console.error('index.html length:', indexHtml.length);
      console.error('contains shadowrootmode:', indexHtml.includes('shadowrootmode'));
      console.error('contains template:', indexHtml.includes('<template'));
      console.error('contains Render Error:', indexHtml.includes('Render Error'));
      console.error('last 300 chars:', indexHtml.substring(indexHtml.length - 300));
    }
    assertEquals(indexHtml.includes('Hello from openElement'), true);
    assertEquals(indexHtml.includes('[object Object]'), false);
  } finally {
    rmSync(tmpRoot, { recursive: true, force: true });
  }
});

Deno.test('create-open: --help flag prints usage info', async () => {
  const help = new Deno.Command(Deno.execPath(), {
    args: ['run', '-A', join(__dirname, '..', 'cli.ts'), '--help'],
    cwd: Deno.makeTempDirSync({ prefix: 'open-help-' }),
    stdout: 'piped',
    stderr: 'piped',
  });
  const result = await help.output();
  const output = new TextDecoder().decode(result.stdout);
  // Should print usage/help info without error
  assertEquals(result.code, 0);
  assert(output.includes('Usage') || output.includes('usage') || output.includes('--help'));
});

Deno.test('create-open: rejects project name with spaces', async () => {
  const tmpRoot = Deno.makeTempDirSync({ prefix: 'open-create-' });
  try {
    const create = new Deno.Command(Deno.execPath(), {
      args: ['run', '-A', join(__dirname, '..', 'cli.ts'), 'my app'],
      cwd: tmpRoot,
      stdout: 'piped',
      stderr: 'piped',
    });
    const result = await create.output();
    const stderr = new TextDecoder().decode(result.stderr);
    const stdout = new TextDecoder().decode(result.stdout);
    // Should fail with an error code and mention the invalid name
    // (exact exit code depends on how the CLI validates input)
    assertExists(
      result.code !== 0 || stderr.includes('my app') || stdout.includes('my app'),
    );
  } finally {
    rmSync(tmpRoot, { recursive: true, force: true });
  }
});
