/**
 * @openelement/adapter-vite - Route Type Generator
 *
 * Generates `.less/routes.d.ts` with type-safe route parameter definitions
 * for the `virtual:less-routes` module. Only routes that have dynamic [param]
 * segments are included in the output.
 *
 * v0.25.0: Initial implementation for build-time route type code generation.
 */

import type { RouteEntry } from '@openelement/core';

/**
 * Convert a file path to a route path, preserving [param] bracket syntax.
 * Unlike `filePathToRoutePath()` in route-scanner (which converts to `:param`
 * for Hono/URLPattern), this preserves `[param]` to match the file-system
 * convention that developers see in their route files.
 *
 * e.g., 'blog/[slug].ts' → '/blog/[slug]'
 * e.g., 'index.ts' → '/'
 */
function filePathToBracketRoute(filePath: string): string {
  let p = filePath.replace(/\.[^.]+$/, '');

  if (p === 'index') return '/';
  if (p.endsWith('/index')) {
    p = p.slice(0, -6);
    if (p === '') return '/';
  }
  if (!p.startsWith('/')) p = '/' + p;

  return p;
}

/**
 * Escape a route path for use as a TypeScript property key.
 * Wraps in quotes to handle paths with special characters.
 */
function escapeRoutePath(path: string): string {
  return JSON.stringify(path);
}

/**
 * Generate TypeScript type literal for route params.
 * Converts param names to a Record<string, string> type.
 *
 * Example: ['slug'] → `{ slug: string }`
 * Example: ['package', 'component'] → `{ package: string; component: string }`
 */
function generateParamsType(params: string[]): string {
  if (params.length === 0) {
    return 'Record<string, never>';
  }
  const fields = params.map((p) => `${p}: string`);
  return `{ ${fields.join('; ')} }`;
}

/**
 * Generate the `.less/routes.d.ts` declaration file content.
 *
 * Only routes that have dynamic parameters (non-empty `params` array)
 * are included in the generated output. Static routes with no params
 * are excluded since they don't need type-safe parameter access.
 *
 * Example output:
 * ```typescript
 * declare module 'virtual:less-routes' {
 *   interface RouteParams {
 *     '/blog/[slug]': { slug: string };
 *     '/registry/[package]/[component]': { package: string; component: string };
 *   }
 * }
 * ```
 *
 * @param routes - Array of route entries from the route scanner
 * @returns TypeScript declaration file content as a string
 */
export function generateRouteTypes(routes: RouteEntry[]): string {
  // Filter for page routes that have dynamic params
  const paramRoutes = routes.filter(
    (r) => r.type === 'page' && r.params && r.params.length > 0,
  );

  if (paramRoutes.length === 0) {
    // No routes with params - generate a placeholder interface
    return [
      '/**',
      ' * Auto-generated by @openelement/adapter-vite (v0.25.0)',
      ' * DO NOT EDIT MANUALLY',
      ' */',
      '',
      "declare module 'virtual:less-routes' {",
      '  // eslint-disable-next-line @typescript-eslint/no-empty-interface',
      '  export interface RouteParams {',
      '  }',
      '}',
      '',
    ].join('\n');
  }

  // Generate entries for each route with params
  const paramEntries = paramRoutes.map((r) => {
    const bracketPath = filePathToBracketRoute(r.filePath);
    const path = escapeRoutePath(bracketPath);
    const type = generateParamsType(r.params!);
    return `    ${path}: ${type};`;
  });

  return [
    '/**',
    ' * Auto-generated by @openelement/adapter-vite (v0.25.0)',
    ' * DO NOT EDIT MANUALLY',
    ' */',
    '',
    "declare module 'virtual:less-routes' {",
    '  export interface RouteParams {',
    ...paramEntries,
    '  }',
    '}',
    '',
  ].join('\n');
}
