import type { HeaderNavLink, NavSection } from '../types.ts';

export interface DocsRouteManifestEntry {
  path: string;
  localizedPaths: Record<string, string>;
  filePath?: string;
  title: string;
  label: string;
  section?: string;
  order?: number;
  layout?: 'home' | 'docs' | 'docs-toc' | 'full-width';
  searchable?: boolean;
  searchText?: string;
  aliases?: string[];
}

export interface DocsRouteManifest {
  locales: string[];
  defaultLocale: string;
  routes: DocsRouteManifestEntry[];
  headerNav: HeaderNavLink[];
  navSections: NavSection[];
}

export function createRouteManifest(options: {
  navSections: NavSection[];
  headerNav: HeaderNavLink[];
  locales?: string[];
  defaultLocale?: string;
}): DocsRouteManifest {
  const locales = options.locales?.length ? options.locales : ['en'];
  const defaultLocale = options.defaultLocale && locales.includes(options.defaultLocale)
    ? options.defaultLocale
    : locales[0];
  const routes: DocsRouteManifestEntry[] = [];

  for (const section of options.navSections) {
    for (const item of section.items) {
      if (item.path.includes(':')) continue;
      routes.push({
        path: item.path,
        localizedPaths: Object.fromEntries(
          locales.map((locale) => [
            locale,
            locale === defaultLocale ? item.path : `/${locale}${item.path}`,
          ]),
        ),
        title: item.label,
        label: item.label,
        section: section.section,
        order: item.order,
        layout: item.path === '/' ? 'home' : 'docs-toc',
        searchable: true,
        searchText: `${item.label} ${section.section}`.trim(),
      });
    }
  }

  return {
    locales,
    defaultLocale,
    routes,
    headerNav: options.headerNav,
    navSections: options.navSections,
  };
}

export function writeRouteManifestModule(manifest: DocsRouteManifest): string {
  return [
    '// Auto-generated by @lessjs/content - do not edit',
    `export const routeManifest = ${JSON.stringify(manifest, null, 2)};`,
    'export const navSections = routeManifest.navSections;',
    'export const headerNav = routeManifest.headerNav;',
  ].join('\n') + '\n';
}
