// Auto-generated by hub:scan — DO NOT EDIT
// To regenerate: deno task hub:scan

type HubTagRecord = {
  tagName: string;
  compatibility: string;
  validationErrors: number;
  validationWarnings: number;
  ssrSnapshot?: string;
};

type HubInstallGuidance = {
  safeToInstall: boolean;
  command: string;
  configChanges: string[];
  warnings: string[];
  ssrCapable: boolean;
};

export type HubPackageRecord = {
  schema: string;
  name: string;
  scope: string;
  version: string;
  source: string;
  repository?: string;
  description?: string;
  homepage?: string;
  manifestHash: string;
  compatibility: string;
  compatibilityJustification: string;
  tags: HubTagRecord[];
  reports: Record<string, string>;
  snapshotPaths: Record<string, string>;
  installGuidance: HubInstallGuidance;
  submittedAt: string;
  submittedBy?: string;
  validatorVersion: string;
};

const _records: Record<string, HubPackageRecord> = {
  "@lessjs/ui": {
    "schema": "hub-package-v1",
    "name": "ui",
    "scope": "@lessjs",
    "version": "0.18.3",
    "source": "local",
    "repository": "https://github.com/lessjs-run/lessjs",
    "description": "LessJS UI component library with DSD-first Lit elements. All components are SSR-capable.",
    "homepage": "https://lessjs.dev",
    "manifestHash": "",
    "compatibility": "ssr-capable",
    "compatibilityJustification": "First-party LessJS package. All components extend DsdLitElement with declared SSR metadata.",
    "tags": [
      {
        "tagName": "less-button",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      },
      {
        "tagName": "less-card",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      },
      {
        "tagName": "less-code-block",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      },
      {
        "tagName": "less-dialog",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      },
      {
        "tagName": "less-hero-ping",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      },
      {
        "tagName": "less-input",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      },
      {
        "tagName": "less-layout",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      },
      {
        "tagName": "less-theme-toggle",
        "compatibility": "ssr-capable",
        "validationErrors": 0,
        "validationWarnings": 0
      }
    ],
    "reports": {
      "validation": "{\"packageName\":\"@lessjs/ui\",\"version\":\"0.18.3\",\"valid\":true,\"compatibility\":\"ssr-capable\",\"tags\":8,\"errors\":[],\"warnings\":[]}"
    },
    "snapshotPaths": {},
    "installGuidance": {
      "safeToInstall": true,
      "command": "less add @lessjs/ui",
      "configChanges": [
        "packages[\"@lessjs/ui\"] — SSR enabled"
      ],
      "warnings": [],
      "ssrCapable": true
    },
    "submittedAt": "2026-05-17T09:18:48.947Z",
    "submittedBy": "hub-scanner",
    "validatorVersion": "0.19.0"
  },
  "@shoelace-style/shoelace": {
    "schema": "hub-package-v1",
    "name": "shoelace",
    "scope": "@shoelace-style",
    "version": "2.20.1",
    "source": "npm",
    "repository": "https://github.com/shoelace-style/shoelace",
    "description": "A forward-thinking library of Web Components. 50+ components for building modern UIs.",
    "homepage": "https://shoelace.style",
    "manifestHash": "",
    "compatibility": "client-only",
    "compatibilityJustification": "Shoelace uses Lit internally but does not publish LessJS SSR metadata. All components are client-only.",
    "tags": [
      {
        "tagName": "sl-alert",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-animated-image",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-avatar",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-badge",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-button",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-card",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-carousel",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-checkbox",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-color-picker",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-details",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-dialog",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-divider",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-drawer",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-dropdown",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-icon",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-icon-button",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-image-comparer",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-input",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-menu",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-menu-item",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-progress-bar",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-radio",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-radio-group",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-range",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-rating",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-select",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-skeleton",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-spinner",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-split-panel",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-switch",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-tab",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-tab-group",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-tab-panel",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-table",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-tag",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-textarea",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-tooltip",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-tree",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "sl-tree-item",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      }
    ],
    "reports": {
      "validation": "{\"packageName\":\"@shoelace-style/shoelace\",\"version\":\"2.20.1\",\"valid\":true,\"compatibility\":\"client-only\",\"tags\":39,\"errors\":[],\"warnings\":[{\"code\":\"NO_LESS_SSR\",\"severity\":\"warning\",\"message\":\"No LessJS SSR metadata found.\"}]}"
    },
    "snapshotPaths": {},
    "installGuidance": {
      "safeToInstall": true,
      "command": "less add @shoelace-style/shoelace",
      "configChanges": [
        "packages[\"@shoelace-style/shoelace\"] — client-only (no SSR)"
      ],
      "warnings": [
        "This package has no SSR metadata. It will render on the client only."
      ],
      "ssrCapable": false
    },
    "submittedAt": "2026-05-17T09:18:48.948Z",
    "submittedBy": "hub-scanner",
    "validatorVersion": "0.19.0"
  },
  "media-chrome": {
    "schema": "hub-package-v1",
    "name": "media-chrome",
    "scope": "",
    "version": "4.19.0",
    "source": "npm",
    "repository": "https://github.com/muxinc/media-chrome",
    "description": "Custom elements for building media player UIs. Browser-dependent media APIs.",
    "homepage": "https://media-chrome.mux.dev",
    "manifestHash": "",
    "compatibility": "client-only",
    "compatibilityJustification": "Media Chrome components depend on browser-specific HTMLMediaElement APIs. Not available in SSR.",
    "tags": [
      {
        "tagName": "media-controller",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "media-play-button",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "media-time-range",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "media-volume-range",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "media-poster-image",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      },
      {
        "tagName": "media-loading-indicator",
        "compatibility": "client-only",
        "validationErrors": 0,
        "validationWarnings": 1
      }
    ],
    "reports": {
      "validation": "{\"packageName\":\"media-chrome\",\"version\":\"4.19.0\",\"valid\":true,\"compatibility\":\"client-only\",\"tags\":6,\"errors\":[],\"warnings\":[{\"code\":\"NO_LESS_SSR\",\"severity\":\"warning\",\"message\":\"No LessJS SSR metadata found.\"}]}"
    },
    "snapshotPaths": {},
    "installGuidance": {
      "safeToInstall": true,
      "command": "less add media-chrome",
      "configChanges": [
        "packages[\"media-chrome\"] — client-only (no SSR)"
      ],
      "warnings": [
        "This package has no SSR metadata. It will render on the client only."
      ],
      "ssrCapable": false
    },
    "submittedAt": "2026-05-17T09:18:48.948Z",
    "submittedBy": "hub-scanner",
    "validatorVersion": "0.19.0"
  }
};

export default _records;
