// Auto-generated by hub:scan — DO NOT EDIT
// To regenerate: deno task hub:scan

export interface HubIndexEntry {
  name: string;
  scope: string;
  version: string;
  description: string;
  compatibility: string;
  tags: string[];
  source: string;
  safeToInstall: boolean;
  ssrCapable: boolean;
  submittedAt: string;
}

export interface HubIndexData {
  schema: string;
  updatedAt: string;
  packages: HubIndexEntry[];
}

const _data: HubIndexData = {
  schema: "hub-index-v1",
  updatedAt: "2026-05-18T03:46:27.945Z",
  packages: [
  {
    "name": "ui",
    "scope": "@lessjs",
    "version": "0.18.3",
    "description": "LessJS UI component library with DSD-first Lit elements. All components are SSR-capable.",
    "compatibility": "ssr-capable",
    "tags": [
      "less-button",
      "less-card",
      "less-code-block",
      "less-dialog",
      "less-hero-ping",
      "less-input",
      "less-layout",
      "less-theme-toggle"
    ],
    "source": "local",
    "safeToInstall": true,
    "ssrCapable": true,
    "submittedAt": "2026-05-18T03:45:39.709Z"
  },
  {
    "name": "shoelace",
    "scope": "@shoelace-style",
    "version": "2.20.1",
    "description": "A forward-thinking library of Web Components. 50+ components for building modern UIs.",
    "compatibility": "client-only",
    "tags": [
      "sl-alert",
      "sl-animated-image",
      "sl-avatar",
      "sl-badge",
      "sl-button",
      "sl-card",
      "sl-carousel",
      "sl-checkbox",
      "sl-color-picker",
      "sl-details",
      "sl-dialog",
      "sl-divider",
      "sl-drawer",
      "sl-dropdown",
      "sl-icon",
      "sl-icon-button",
      "sl-image-comparer",
      "sl-input",
      "sl-menu",
      "sl-menu-item",
      "sl-progress-bar",
      "sl-radio",
      "sl-radio-group",
      "sl-range",
      "sl-rating",
      "sl-select",
      "sl-skeleton",
      "sl-spinner",
      "sl-split-panel",
      "sl-switch",
      "sl-tab",
      "sl-tab-group",
      "sl-tab-panel",
      "sl-table",
      "sl-tag",
      "sl-textarea",
      "sl-tooltip",
      "sl-tree",
      "sl-tree-item"
    ],
    "source": "npm",
    "safeToInstall": true,
    "ssrCapable": false,
    "submittedAt": "2026-05-18T03:46:27.902Z"
  },
  {
    "name": "media-chrome",
    "scope": "",
    "version": "4.19.0",
    "description": "Custom elements for building media player UIs. Browser-dependent media APIs.",
    "compatibility": "client-only",
    "tags": [
      "media-controller",
      "media-play-button",
      "media-time-range",
      "media-volume-range",
      "media-poster-image",
      "media-loading-indicator"
    ],
    "source": "npm",
    "safeToInstall": true,
    "ssrCapable": false,
    "submittedAt": "2026-05-18T03:46:27.911Z"
  }
],
};

export default _data;
