/**
 * Registry Hub - Package Search & List
 *
 * v0.19.0: Browse and search validated Web Component packages.
 * Data is embedded during SSG via JSON import, no client-side fetch needed.
 *
 * @see docs/sop/v0.19.0-platform-hub.md
 * @see ADR-0030
 */

export const meta = { section: 'Registry', label: 'Package Registry', order: 5 };

import { DsdElement } from '@lessjs/core';
import { StyleSheet } from '@lessjs/style-sheet';
import { openPropsTokenSheet } from '@lessjs/ui/open-props-tokens';
import { headerNav, navSections } from '@lessjs/content/nav';
import '@lessjs/ui/less-layout';

// ─── Data ────────────────────────────────────────────────────────────────
// Data is imported at build time from hub-data.ts (generated by hub:scan).
// During SSR/SSG: the full data is inlined into the TS module.
// During dev: the same import works because the file exists.

import hubData from '../../data/registry/hub-index.ts';
import type { HubIndexData, HubIndexEntry } from '../../data/registry/hub-index.ts';

export const tagName = 'docs-registry-home';

const COMPAT_LABELS: Record<string, string> = {
  'ssr-capable': 'SSR Capable',
  'client-only': 'Client Only',
  'rejected': 'Rejected',
  'experimental-dom': 'Experimental DOM',
};

const COMPAT_COLORS: Record<string, string> = {
  'ssr-capable': 'var(--success)',
  'client-only': 'var(--warning)',
  'rejected': 'var(--error)',
  'experimental-dom': 'var(--info)',
};

const routeSheet = new StyleSheet();

routeSheet.replaceSync(`
      .registry-header {
        margin-bottom: var(--size-8);
      }

      .registry-header h1 {
        font-size: var(--font-size-4);
        font-weight: var(--font-weight-7);
        margin: 0 0 0.5rem;
      }

      .registry-header p {
        color: var(--text-secondary);
        margin: 0;
        font-size: 0.9375rem;
      }

      .badge-early-access {
        display: inline-block;
        font-size: 0.625rem;
        font-weight: var(--font-weight-6);
        text-transform: uppercase;
        letter-spacing: 0.05em;
        padding: 0.15em 0.5em;
        border-radius: var(--radius-1);
        background: var(--brand-subtle);
        color: var(--brand);
        vertical-align: middle;
        margin-left: 0.5rem;
      }

      .early-access-note {
        margin-top: 0.5rem !important;
        font-size: 0.8125rem !important;
        font-style: italic;
      }

      .early-access-note a {
        color: var(--brand);
        text-decoration: underline;
      }

      /* Controls */
      .controls {
        display: flex;
        gap: var(--size-4);
        align-items: center;
        margin-bottom: var(--size-6);
        flex-wrap: wrap;
      }

      .search-box {
        flex: 1;
        min-width: 200px;
        padding: 0.625rem 0.875rem;
        border: 0.5px solid var(--border);
        border-radius: 6px;
        background: var(--bg-surface);
        color: var(--text-primary);
        font-size: var(--font-size-0);
        outline: none;
        transition: border-color 0.15s;
      }

      .search-box:focus {
        border-color: var(--brand);
        box-shadow: 0 0 0 3px var(--brand-glow, rgba(83,74,183,0.35)), var(--shadow-glow, 0 0 20px rgba(83,74,183,0.15));
      }

      .search-box::placeholder {
        color: var(--text-muted);
      }

      .filter-group {
        display: flex;
        gap: 0.25rem;
        flex-wrap: wrap;
      }

      .sort-select {
        padding: 0.375rem 0.5rem;
        border: 0.5px solid var(--border);
        border-radius: 14px;
        background: transparent;
        color: var(--text-secondary);
        font-size: var(--font-size-00);
        cursor: pointer;
      }

      .filter-btn {
        padding: 0.375rem 0.75rem;
        border: 0.5px solid var(--border);
        border-radius: 14px;
        background: transparent;
        color: var(--text-secondary);
        font-size: var(--font-size-00);
        cursor: pointer;
        transition: all 0.15s;
        white-space: nowrap;
      }

      .filter-btn:hover {
        border-color: var(--border-hover);
        color: var(--text-primary);
      }

      .filter-btn.active {
        background: var(--brand);
        border-color: var(--brand);
        color: white;
      }

      /* Stats */
      .stats {
        font-size: 0.8125rem;
        color: var(--text-muted);
        margin-bottom: var(--size-4);
      }

      /* Package List - grid layout (v0.19.1 Phase 6, ADR-0035 B3) */
      .package-list {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
        gap: var(--size-4);
      }

      .package-card {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
        padding: var(--size-5);
        border: 1px solid var(--border);
        border-radius: 10px;
        background: var(--bg-surface);
        box-shadow: 0 1px 4px rgba(0,0,0,0.04);
        transition: border-color 0.2s, box-shadow 0.2s, transform 0.2s;
        cursor: pointer;
        text-decoration: none;
        color: inherit;
      }

      .package-card:hover {
        border-color: var(--brand);
        box-shadow: var(--shadow-brand-md, 0 4px 20px rgba(83,74,183,0.3));
        transform: translateY(-3px);
      }

      .package-info {
        flex: 1;
        min-width: 0;
      }

      .package-name {
        font-size: var(--font-size-1);
        font-weight: var(--font-weight-6);
        margin: 0 0 0.25rem;
        display: flex;
        align-items: center;
        gap: 0.5rem;
        flex-wrap: wrap;
      }

      .package-name code {
        font-size: var(--font-size-0);
        background: var(--bg-code);
        padding: 0.125rem 0.375rem;
        border-radius: 3px;
      }

      .package-version {
        font-size: var(--font-size-00);
        color: var(--text-muted);
        font-weight: var(--font-weight-4);
      }

      .package-desc {
        font-size: 0.8125rem;
        color: var(--text-secondary);
        margin: 0.25rem 0;
        line-height: 1.5;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
      }

      .package-meta {
        display: flex;
        gap: 0.5rem;
        align-items: center;
        flex-wrap: wrap;
        margin-top: 0.375rem;
      }

      .compat-badge {
        display: inline-flex;
        align-items: center;
        gap: 0.25rem;
        padding: 0.125rem 0.5rem;
        border-radius: 10px;
        font-size: 0.6875rem;
        font-weight: var(--font-weight-5);
        white-space: nowrap;
      }

      .compat-dot {
        width: 6px;
        height: 6px;
        border-radius: 50%;
        display: inline-block;
      }

      .tag-pill {
        display: inline-block;
        padding: 0.0625rem 0.375rem;
        background: var(--bg-code);
        border-radius: 3px;
        font-size: 0.6875rem;
        color: var(--text-muted);
      }

      .install-badge {
        display: inline-flex;
        align-items: center;
        gap: 0.25rem;
        font-size: 0.6875rem;
        padding: 0.125rem 0.375rem;
        border-radius: 3px;
      }

      .install-safe {
        background: var(--success-subtle);
        color: var(--success);
      }

      .install-unsafe {
        background: var(--error-subtle);
        color: var(--error);
      }

      .new-badge {
        display: inline-flex;
        align-items: center;
        gap: 0.25rem;
        font-size: 0.625rem;
        font-weight: var(--font-weight-6);
        padding: 0.0625rem 0.375rem;
        border-radius: 6px;
        background: var(--info-subtle);
        color: var(--info);
        text-transform: uppercase;
        letter-spacing: 0.025em;
      }

      .component-breakdown {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        font-size: 0.6875rem;
        color: var(--text-muted);
      }

      .breakdown-segment {
        display: inline-flex;
        align-items: center;
        gap: 0.25rem;
      }

      .breakdown-dot {
        width: 6px;
        height: 6px;
        border-radius: 50%;
        display: inline-block;
      }

      .empty-state {
        text-align: center;
        padding: var(--size-12) var(--size-4);
        color: var(--text-muted);
        font-size: 0.9375rem;
      }

      @media (max-width: 640px) {
        .controls {
          flex-direction: column;
          align-items: stretch;
        }
      }
    `);

export default class DocsRegistryHome extends DsdElement {
  private _packages: HubIndexEntry[] = [];
  private _filtered: HubIndexEntry[] = [];
  private _query = '';
  private _tierFilter = 'all';
  private _sortBy: 'name' | 'tags' | 'compatibility' = 'name';
  private _loading = true;

  static override styles = [openPropsTokenSheet, routeSheet];

  // ─── Lifecycle ────────────────────────────────────────────────────────
  // Data is available at import time from hub-data.ts.
  // Constructor loads data synchronously so render() has it during SSR/SSG.
  // On the client, the same import is used - no fetch needed.

  constructor() {
    super();
    const index = hubData as HubIndexData;
    if (index && index.packages) {
      this._packages = index.packages || [];
      this._filtered = [...this._packages];
    }
    this._loading = index && index.packages ? false : true;
  }

  private _onSearch(e: InputEvent) {
    this._query = (e.target as HTMLInputElement).value;
    this._applyFilters();
  }

  private _setFilter(tier: string) {
    this._tierFilter = tier;
    this._applyFilters();
  }

  private _applyFilters() {
    let result = [...this._packages];

    const q = this._query.toLowerCase();
    if (q.length >= 2) {
      result = result.filter((p) => {
        const fullName = p.scope ? `${p.scope}/${p.name}` : p.name;
        if (fullName.toLowerCase().includes(q)) return true;
        if (p.description?.toLowerCase().includes(q)) return true;
        for (const tag of p.tags) {
          if (tag.toLowerCase().includes(q)) return true;
        }
        return false;
      });
    }

    if (this._tierFilter !== 'all') {
      result = result.filter((p) => p.compatibility === this._tierFilter);
    }

    // Sort
    result.sort((a, b) => {
      switch (this._sortBy) {
        case 'tags':
          return b.tags.length - a.tags.length;
        case 'compatibility': {
          const order: Record<string, number> = {
            'ssr-capable': 0,
            'client-only': 1,
            'experimental-dom': 2,
            'rejected': 3,
          };
          return (order[a.compatibility] ?? 9) - (order[b.compatibility] ?? 9);
        }
        default: {
          const aName = a.scope ? `${a.scope}/${a.name}` : a.name;
          const bName = b.scope ? `${b.scope}/${b.name}` : b.name;
          return aName.localeCompare(bName);
        }
      }
    });

    this._filtered = result;
    this.update();
  }

  private _packageLink(pkg: HubIndexEntry): string {
    const name = pkg.scope ? `${pkg.scope}/${pkg.name}` : pkg.name;
    return `/registry/${name.replace('/', '~')}`;
  }

  override render() {
    return `
      <less-layout
        nav-items='${JSON.stringify(navSections)}'
        header-nav='${JSON.stringify(headerNav)}'
        current-path="/registry"
        locale="en"
        locales='${JSON.stringify(['en'])}'
      >
        <div class="container">
          <div class="registry-header">
            <h1>Registry Hub <span class="badge-early-access">Early Access</span></h1>
            <p>
              Discover validated Web Component packages. Each package includes compatibility evidence,
              installation guidance, and snapshot previews.
            </p>
            <p class="early-access-note">
              🚧 Currently indexing 3 packages. We're actively onboarding more Web Components libraries.
              <a href="https://github.com/lessjs-run/lessjs/issues?q=label%3Ahub-submit">Submit your package -></a>
            </p>
          </div>

          <div class="controls">
            <input
              class="search-box"
              type="text"
              placeholder="Search by name, tag, or description..."
              @input="${this._onSearch}"
              .value="${this._query}"
            >
            <div class="filter-group">
              <button
                class="filter-btn ${this._tierFilter === 'all' ? 'active' : ''}"
                @click="${() => this._setFilter('all')}"
              >
                All
              </button>
              <button
                class="filter-btn ${this._tierFilter === 'ssr-capable' ? 'active' : ''}"
                @click="${() => this._setFilter('ssr-capable')}"
              >
                SSR ✓
              </button>
              <button
                class="filter-btn ${this._tierFilter === 'client-only' ? 'active' : ''}"
                @click="${() => this._setFilter('client-only')}"
              >
                Client
              </button>
              <button
                class="filter-btn ${this._tierFilter === 'rejected' ? 'active' : ''}"
                @click="${() => this._setFilter('rejected')}"
              >
                Rejected
              </button>
            </div>
            <select class="sort-select" @change="${(e: Event) => {
      this._sortBy = (e.target as HTMLSelectElement).value as
        | 'name'
        | 'tags'
        | 'compatibility';
      this._applyFilters();
    }}">
              <option value="name" ?selected="${this._sortBy === 'name'}">Sort: Name</option>
              <option value="tags" ?selected="${this._sortBy === 'tags'}">Sort: Components</option>
              <option value="compatibility" ?selected="${
      this._sortBy ===
        'compatibility'
    }">Sort: Compatibility</option>
            </select>
          </div>

          ${
      this._loading
        ? `
              <div class="empty-state">Loading registry...</div>
            `
        : this._filtered.length === 0
        ? `
              <div class="empty-state">
                ${
          this._query || this._tierFilter !== 'all'
            ? 'No packages match your search criteria.'
            : 'No packages in the registry yet.'
        }
              </div>
            `
        : `
              <div class="stats">${this._filtered.length} package${
          this._filtered.length !== 1 ? 's' : ''
        } found</div>

              <div class="package-list">
                ${
          this._filtered.map((pkg) => {
            const fullName = pkg.scope ? `${pkg.scope}/${pkg.name}` : pkg.name;
            const compatLabel = COMPAT_LABELS[pkg.compatibility] || pkg.compatibility;
            const compatColor = COMPAT_COLORS[pkg.compatibility] || '#888';

            // "New" badge: submitted within 7 days
            const submittedDate = new Date(pkg.submittedAt);
            const daysSinceSubmit = (Date.now() - submittedDate.getTime()) /
              (1000 * 60 * 60 * 24);
            const isNew = daysSinceSubmit < 7;

            // SSR vs client component breakdown
            const totalTags = pkg.tags.length;
            const ssrCount = pkg.ssrCapable ? totalTags : 0;
            const clientCount = totalTags - ssrCount;

            return `
                    <a class="package-card" href="${
              this._packageLink(pkg)
            }" data-compat="${pkg.compatibility}">
                      <div class="package-info">
                        <div class="package-name">
                          <code>${fullName}</code>
                          <span class="package-version">v${pkg.version}</span>
                          ${
              isNew
                ? `
                              <span class="new-badge">New</span>
                            `
                : ''
            }
                        </div>
                        <div class="package-desc">${pkg.description || 'No description'}</div>
                        <div class="package-meta">
                          <span class="compat-badge" style="background:${compatColor}15;border:0.5px solid ${compatColor}40;">
                            <span class="compat-dot" style="background:${compatColor}"></span>
                            ${compatLabel}
                          </span>
                          <span class="install-badge ${
              pkg.safeToInstall ? 'install-safe' : 'install-unsafe'
            }">
                            ${pkg.safeToInstall ? '✅ Safe install' : '❌ Not installable'}
                          </span>
                          <span class="component-breakdown">
                            ${
              ssrCount > 0
                ? `
                                <span class="breakdown-segment">
                                  <span class="breakdown-dot" style="background:var(--success)"></span>${ssrCount} SSR
                                </span>
                              `
                : ''
            } ${
              clientCount > 0
                ? `
                                <span class="breakdown-segment">
                                  <span class="breakdown-dot" style="background:var(--warning)"></span>${clientCount} client
                                </span>
                              `
                : ''
            }
                          </span>
                        </div>
                      </div>
                    </a>
                  `;
          })
        }
              </div>
            `
    }
        </div>
      </less-layout>
    `;
  }
}

// Guard against duplicate define
if (!customElements.get(tagName)) {
  customElements.define(tagName, DocsRegistryHome);
}
