/**
 * @openelement/i18n - i18n data loader
 *
 * Pure function for loading i18n configuration.
 * Zero module-level state.
 *
 * ADR 0018: Replaces the old stateful initI18nData() + getI18nOptions() pattern.
 * Route components import data from @openelement/generated/i18n instead.
 * This module is only called by the virtual module plugin's load() hook.
 */

import type { LessI18nOptions } from './types.ts';

/**
 * Pure function: load i18n configuration.
 * No module-level state. No side effects.
 *
 * This replaces the stateful initI18nData() + getI18nOptions() pattern.
 * For virtual module consumers, use @openelement/generated/i18n instead.
 */
export function loadI18nData(options: LessI18nOptions): LessI18nOptions {
  return {
    ...options,
    locales: [...options.locales],
  };
}

/**
 * Generate TypeScript module source code for i18n configuration.
 * The output is a self-contained .ts file that exports locales,
 * defaultLocale, and helper functions.
 *
 * SOP-001: Virtual Modules Removal — replaces @openelement/generated/i18n.
 *
 * @param locales - Array of locale code strings (e.g. ['en', 'zh'])
 * @param defaultLocale - Default locale code (e.g. 'en')
 * @returns TypeScript module source string
 */
export function writeI18nDataModule(locales: string[], defaultLocale: string): string {
  return [
    '// Auto-generated by @openelement/i18n — do not edit',
    `export const locales = ${JSON.stringify(locales)};`,
    `export const defaultLocale = "${defaultLocale}";`,
    '',
    'export function getDefaultLocale(): string { return defaultLocale; }',
    'export function getI18nOptions() { return { locales, defaultLocale }; }',
  ].join('\n') + '\n';
}
